### ISSUE TITLE
flushToDiskInterval is not working?

### ISSUE THREAD

**Issue by BirolAYDIN** [serilog/serilog#1943] opened 2023-08-01 09:15 UTC
flushToDiskInterval not working. By adding it to the appsettings.json file, it writes the logs to disk without waiting for the time when used.

**Comment by nblumhardt** [comment] 2023-08-01 09:56
Hi! Logs _can_ still be written to disk without a flush. The flush _guarantees_ that the logs are written to disk.

Hope this helps,
Nick

**Comment by bartelink** [comment] 2023-08-01 09:58
This repo is for the core Serilog package.

For usage questions and sink specific questions, it's more appropriate to ask a question on stackoverflow.com
- you'll get way more eyes (including anyone that's bothered to watch or answer here)
- its a better forum for to/froing on what the problem is (you have given zero hints as to the sink you are using, or anything about your environment, or a repro code sample)

When you've logged the question, feel free to post a link here as you close it, but in general it's best to conserve the time of the maintainers by not littering this repo's issue list with one liner questions where people have to guess what you're after.

**Comment by BirolAYDIN** [comment] 2023-08-01 10:19
Hi!. In appsettings.json, for example, when I set the value as "flushToDiskInterval": "00:00:10", is it normal for it to write directly to the disk without waiting for the time?

**Comment by bartelink** [comment] 2023-08-01 12:23
See above. This is not a chat forum. Can you imagine the effect if even [.01% of the downloads of this package](https://www.nuget.org/stats/packages/Serilog?groupby=Version) were to come here and ask random questions?
If you post your question on SO and put a link here, I'll read your question.
(I personally would also look at the code - the code is pretty legible IME and is way quicker than chatting)

**Closed** 2023-08-31 02:30 UTC
