### ISSUE TITLE
Serilog FileSink - increment revision not created after IIS App pool is recycled

### ISSUE THREAD

**Issue by UmaMuthumani** [serilog/serilog#1240] opened 2018-10-25 15:56 UTC
We are seeing an issue using Serilog in Asp.Net Core 2.1 application .In IIS,   when application pool is recycled, further file logging stops . 
**Current Behavior:**
Once application pool is restarted, Serilog file doesn’t create numbered postfixes file( _001) nor updates the existing log file for the day. Do we need to include any additional configuration than below? 
**Expected Behavior**
Once application pool is restarted, Serilog file should create numbered postfixes(like _001) for new file log entry.
 **Packages and their versions used in Asp.Netcore 2.1 application -** Serilog.AspNetCore 2.1.1, Serilog.Sinks.File 4.0.0  , Serilog.Settings.Configuration 3.0.1 
Program.cs  - Main
   
            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json");

            Configuration = builder.Build();
            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .CreateLogger();
            try
            {
                CreateWebHostBuilder(args).Build().Run();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
            }
            finally
            {
                Log.CloseAndFlush();
            }

CreateWebHostBuilder - .UseSerilog();
Appsettings.json
"Serilog": {
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "Path": "C:\\Data\\logs\\applog.log",
          "rollingInterval": "Day",
          "retainedFileCountLimit": "30",
          "shared": true
        }
      }
    ]
  }
Do we need to include any additional configuration than detailed here?

**Comment by nblumhardt** [comment] 2018-10-25 22:14
Hi @UmaMuthumani - nothing obvious stands out from the configuration. You may find some additional information if you enable `SelfLog`: https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics - HTH!

**Comment by UmaMuthumani** [comment] 2018-10-26 12:11
Hi @nblumhardt  , Its actually escaped with \\ in the JSON file on server. File logs works fine, if I delete the  existing log file for the current date , and after app pool restarts, file is created and logged.
Issue is when a file for the current date exists and app pool is restarted manually or through TFS deploy which would eventually restart the app pool.

The exception of file being locked message, seems like app pool needs to open a log file still locked by the outgoing process. My understanding in this case is, it would create a _001 file for new worker process. 
I even tried giving  "shared": false, "flushToDiskInterval": "00:00:05" to see if it makes a difference  and might created numbered postfixes file.
 "Serilog": {
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "Path": "D:\\AppErrors\\AppName\\AppName.log",
          "rollingInterval": "Day",
          "retainedFileCountLimit": "120",
          "shared": true
        }
      }
    ]
  }

**Comment by skomis-mm** [comment] 2018-10-27 19:55
> at System.IO.FileStream..ctor...
at Serilog.Sinks.File.FileSink..ctor...
at Serilog.Sinks.File.RollingFileSink.OpenFile...
at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo...

@UmaMuthumani looking at this stack trace I see it was created with sharing mode [disabled](https://github.com/serilog/serilog-sinks-file/blob/master/src/Serilog.Sinks.File/Sinks/File/RollingFileSink.cs#L147). Otherwise it would include `SharedFileSink`. 

Can you paste a stack trace from the `SelfLogDiagonistics` with sharing mode enabled?
(I couldn't reproduce this when `shared` is true)

**Comment by UmaMuthumani** [comment] 2018-10-29 04:29
Hi @skomis-mm , Updated the config to  have shared:true. The stack trace from my project application is as below
2018-10-29T02:44:52.3083658Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.UnauthorizedAccessException: Access to the path 'D:\AppErrors\AppName\AppName.log' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Serilog.Sinks.File.SharedFileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding)
   at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable`1 minSequence)
   at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)
   at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
2018-10-29T02:44:52.4122327Z Ignoring added logger provider Serilog.Extensions.Logging.SerilogLoggerProvider

I created a plain .net core API application from scratch which has nothing but asp.net core api template with a  default controller.Added the details required for serilog and swagger packages .Even that has the same issue. The strack trace of that  is
2018-10-29T03:09:46.5030318Z Unable to open file sink for D:\AppErrors\CoreWebApp\CoreWebApp.log: System.UnauthorizedAccessException: Access to the path 'D:\AppErrors\CoreWebApp\CoreWebApp.log' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Serilog.Sinks.File.SharedFileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding)
   at Serilog.FileLoggerConfigurationExtensions.ConfigureFile(Func`4 addSink, ITextFormatter formatter, String path, LogEventLevel restrictedToMinimumLevel, Nullable`1 fileSizeLimitBytes, LoggingLevelSwitch levelSwitch, Boolean buffered, Boolean propagateExceptions, Boolean shared, Nullable`1 flushToDiskInterval, Encoding encoding, RollingInterval rollingInterval, Boolean rollOnFileSizeLimit, Nullable`1 retainedFileCountLimit)
App runs in Windows server 2012 R2 with asp.net core module installed in IIS. I see this issue on server only.
Attached is the .net core template app tested in Webserver .
[CoreWebApp.zip](https://github.com/serilog/serilog/files/2523763/CoreWebApp.zip)

**Comment by nblumhardt** [comment] 2018-10-29 05:33
Hi @UmaMuthumani - does the Windows user account that the IIS app pool is running under have access to the `D:\AppErrors\AppName\AppName.log` path? Cheers!

**Comment by UmaMuthumani** [comment] 2018-10-30 02:05
Hi @nblumhardt , @skomis-mm , Issue is now resolved. The fix is to  give application service account full control to D:\AppErrors folder on server. Now, Logging happens in same file even after IIS restart!!

It didnt come across my mind initially,   that it would be a a folder access issue for the account on which app is running on IIS, as file logging to the same path works fine  without issues when log is created for the 1st time.

Thanks much for the response and providing suggestions !

**Comment by merbla** [comment] 2018-10-30 05:48
Closing this one out. Fix as per notes above.

**Closed by merbla** 2018-10-30 05:48 UTC
