### ISSUE TITLE
the "Override" doesn't work？

### ISSUE THREAD

**Issue by maobiwen** [serilog/serilog#2106] opened 2024-08-27 08:18 UTC
My project is based on .NET Core 7 and uses Serilog as the logging tool. I want the overall log output to be at the Information level by default, but I also want the logs under a specific namespace to be at the Debug level. My Serilog configuration is in Image 1, and the .NET Core program startup code is in Image 2. When I use Log.Debug("debug"); to write logs, the logs are not printed to the console, but when I use _logger.LogDebug("logDebug"); the logs are printed to the console. What could be the reason for this?
[](url)
![Serilogconf](https://github.com/user-attachments/assets/72b9ad42-cf3c-478b-a2d1-6d3beef836bb)
![programcs](https://github.com/user-attachments/assets/2f31fc57-795e-4580-981d-3a9d6941520c)
![mykongzhiqi](https://github.com/user-attachments/assets/11894f29-058c-4dd9-a336-1d3721843f16)

**Comment by bartelink** [comment] 2024-08-27 10:20
Duplicate of https://stackoverflow.com/questions/78917803/why-doesnt-the-minimumlevel-in-serilog-work#comment139142019_78917803
Please refrain from asking usage questions here - as the fact I saw ti there demonstrates, people that watch this repo watch SO and respond there quicker

**Closed by bartelink** 2024-08-27 10:20 UTC
Labels: bug
