### ISSUE TITLE
'ILogger' is incredibly hard to decorate

### ISSUE THREAD

**Issue by julealgon** [serilog/serilog#1509] opened 2020-12-03 22:04 UTC
**Is your feature request related to a problem? Please describe.**
I was considering creating a decorator for `ILogger` to manipulate the log level on log calls, but this is nearly unfeasible due to the insane amount of methods/overloads that are part of the interface. The interface has 50+ members.

**Describe the solution you'd like**
I believe a better design would be to move most methods and "helper" overloads into extension methods, and keep only the core functionality on the interface. This is what `Microsoft.Extensions.Logging.Logger` does: their interface is extremely focused, and helper overloads are offered as separate extension methods.

This makes it incredibly easy to extend the funcionality of `Microsoft.Extensions.Logging.ILogger` while benefiting from all the same extension methods.

**Describe alternatives you've considered**
I've given up in creating a decorator for Serilog's `ILogger`, as that would end up generating an unmanageable amount of boilerplate code. I went with a decorator on `Microsoft.Extensions.Logging.ILogger` instead.

I understand I could probably create a custom Sink that performs what I need, but that's (in my opinion) a more convoluted alternative that complicates configuration substantially by introducing another sink indirection.

**Additional context**
To elaborate on "why" I considered a decorator, I have a requirement that all logs from the application can only fall into "debug", "info", "warn" and "error" levels. At the same time, I don't want to limit what the application does right now based on this specific requirement which could very well change in the future (it is an implementation detail of the log aggregator we are using), so I thought about "converting `Fatal` events into `Error` ones", and the most straightforward approach (conceptually) I considered was a decorator: on every call, "just check for `Fatal` and pass `Error` along", easy, right? As soon as one sees the number of members in `ILogger`, this approach is immediately discarded.

Here is how easy it is when the interface is better designed:

```csharp
    internal sealed class CriticalAsErrorLogger : LoggerDecorator
    {
        public CriticalAsErrorLogger(ILogger logger)
            : base(logger)
        {
        }

        public override void Log<TState>(
            LogLevel logLevel,
            EventId eventId,
            TState state,
            Exception exception,
            Func<TState, Exception, string> formatter)
        {
            base.Log(
                logLevel is Critical ? Error : logLevel,
                eventId,
                state,
                exception,
                formatter);
        }
    }
```

**Comment by nblumhardt** [comment] 2020-12-03 22:28
You need the latest Serilog and a recent C#/.NET Core runtime - since 2.10, Serilog provides default implementations for just about everything on `ILogger`, so decorating it only requires a couple of overloads.

Duplicate of https://github.com/serilog/serilog/issues/861

**Closed by nblumhardt** 2020-12-03 22:28 UTC
Labels: enhancement

**Comment by julealgon** [comment] 2020-12-04 12:19
Thanks for clarifying Nick. Searched and didn't find anything related with "decorator" but the concern raised by Steven is indeed pretty similar indeed.

I did not realize `ILogger` was using default interface implementations now. Will look into it.

Having said that, I'm not entirely sure it "solves" my problem though. Say, for instance, that the concrete Serilog implementation does some optimization by overriding the default implementation of one of the "default implemented members". If I create a decorator on the interface, and _do not redirect those method_, them I'll end up forcing the default implementations instead of the customized ones from the concrete class, right?

In that sense, to make this work "properly" and allow for any kinds of specific reimplementations, I'd still need to redirect all 50+ methods from my decorator class.

If that's really the case, then the extension method approach I described would be a better fit for this.

Let me know if this makes sense. I've not used default implementations so far so I might be grasping at straws here.

**Comment by nblumhardt** [comment] 2020-12-04 21:26
The default implementations almost all forward to a couple of key methods - `Write()` and `IsEnabled()`. Most decorators would require implementing `Write()` only. Give it a shot - hopefully you'll be surprised how smoothly it works, now :+1:

**Comment by julealgon** [comment] 2020-12-04 22:51
> Give it a shot - hopefully you'll be surprised how smoothly it works, now 👍

I'm not really concerned with how much effort would be needed at this point, but with the correctness of declaring a decorator that does not forward all interface methods.

> The default implementations almost all forward to a couple of key methods - Write() and IsEnabled(). Most decorators would require implementing Write() only. 

See, that's the point. If I create a decorator with this knowledge in mind, I'm not relying on the abstraction anymore, but on the implementation. If the concrete implementation changes later and implements some of those currently-interface-only members, then my decorator suddenly starts producing incorrect output by falling back to the original implementation again.

For example:
```csharp
    public interface ISomething
    {
        int DoIt();

        int DoItBetterInTheFutureMaybe() => this.DoIt();
    }
```
Imagine we have this, and then I create a decorator like:
```csharp
    public abstract class SomethingDecorator : ISomething
    {
        private readonly ISomething something;

        protected SomethingDecorator(ISomething something)
        {
            this.something = something;
        }

        public int DoIt() => this.something.DoIt();
    }
```

That sounds good, however, what happens if I apply this decorator to a concrete instance like this?
```csharp
    public sealed class Something : ISomething
    {
        int ISomething.DoIt() => 0;

        int ISomething.DoItBetterInTheFutureMaybe() => 1;
    }
```

```csharp
        [TestMethod]
        public void DecoratorsWithDefaultInterfaceImplementationsAreScary()
        {
            var something = new Something();
            ISomething somethingDecorator = new SomethingElse(something);
            var x = somethingDecorator.DoItBetterInTheFutureMaybe();

            _ = x.Should().Be(1); // FAILS, returns 0
        }
```

Now suddenly if I use the decorator, I get different results than if I just use the actual instance directly.

This is the first time I thought about this problem really, but these interface implementations are actually quite dangerous for decorators :S

I'm especially surprised by the automatic refactor from Visual Studio, which does _not_ implement the second method for me automatically when using the wrapper refactor option:
![image](https://user-images.githubusercontent.com/461579/101223070-e0728680-3669-11eb-9045-230cd7861cbb.png)

Man...

**Comment by nblumhardt** [comment] 2020-12-06 22:28
:-) yeah, there's no silver bullet, unfortunately.

Serilog takes/has always taken backwards-compatibility very seriously, though. It's possible some future version may break something, here, but that's going to be the case with most extension points.
