### ISSUE TITLE
Logger Dispose takes too long

### ISSUE THREAD

**Issue by mschiltknecht** [serilog/serilog#1917] opened 2023-06-13 13:42 UTC
**Description**
When _logger.LogInformation("some text") is called at least once, the dispose method takes about 8 seconds longer than without the _logger.LogInformation() call, even when backend is not runnig.

**Reproduction**
See unit test that demonstrates the issue: https://github.com/mschiltknecht/LoggerDisposeTest

**Expected behavior**
Unit test should not fail / Dispose should not take as much time.

**Comment by nblumhardt** [comment] 2023-06-20 02:57
Hi! Chances are good that this is due to the sink you're using being flushed during disposal. If you think there's something else going on please let us know; otherwise there's not much to go on, here. Thanks!

**Comment by nblumhardt** [comment] 2023-09-20 01:24
Closing as we don't have much to run with; the sink trying to make a network request to flush on dispose seems like expected behavior. If you turn up any more info that suggests there's something unexpected happening, please let us know, though! :-)

**Closed by nblumhardt** 2023-09-20 01:24 UTC
Labels: bug
