### ISSUE TITLE
Logger remove bracket when more than 2 brackets in a string

### ISSUE THREAD

**Issue by antonysc** [serilog/serilog#1258] opened 2018-12-14 18:45 UTC
example with this code will write in file  }}---}}

new LoggerConfiguration()
                .WriteTo.File(fullFilePath, outputTemplate:"{Message}{NewLine}",
                    rollingInterval: RollingInterval.Day, rollOnFileSizeLimit: true,
                    fileSizeLimitBytes: 100000000)
                .CreateLogger().Information("}}}---}}}");

**Comment by adamchester** [comment] 2018-12-15 03:07
Hi @antonysc, thanks for stopping by.

This is expected behaviour.

The reason is because the `Information` method (and many others like it in Serilog) are actually expecting you to provide a message templates.

Please visit this page for details: https://github.com/serilog/serilog/wiki/Writing-Log-Events

I’ll close this issue now, but please feel free to reopen this issue if you think it’s not solved.

**Closed by adamchester** 2018-12-15 03:07 UTC

**Comment by t-briz** [comment] 2023-09-14 23:59
Hi.
I am trying to log the below json. 
It makes it easier for our devs to pull this from the logs and pump it into postman to quickly troubleshoot payloads.
However, Serilog keeps removing the brackets, and I cannot find a "literal string" type function for logging this.
So in short: How would I get serilog to stop removing }}} from this?

{
  "RequestId": "FB7BB13D9B375CACF50055E02FF88909",
  "OriginalRequestId": "Q00141",
  "RequestingPartyCode": "DFQD",
  "SerivceDate": null,
  "ServiceType": "PICKUP",
  "TotalWeight": {
    "Value": 1794,
    "Unit": "lb"
  },
  "TotalVolume": {
    "Value": 105.22685185185185,
    "Unit": "cu ft"
  },
  "CargoItems": [
    {
      "Pieces": 1,
      "FreightClass": "70",
      "Weight": {
        "Value": 874,
        "Unit": "lb"
      },
      "Dimensions": {
        "Length": {
          "Value": 93,
          "Unit": "in"
        },
        "Width": {
          "Value": 28,
          "Unit": "in"
        },
        "Height": {
          "Value": 34,
          "Unit": "in"
        }
      }
    },
    {
      "Pieces": 1,
      "FreightClass": "70",
      "Weight": {
        "Value": 920,
        "Unit": "lb"
      },
      "Dimensions": {
        "Length": {
          "Value": 98,
          "Unit": "in"
        },
        "Width": {
          "Value": 28,
          "Unit": "in"
        },
        "Height": {
          "Value": 34,
          "Unit": "in"
        }
      }
    }
  ],
  "Shipper": {
    "Name": "",
    "Address": {
      "StreetAddress1": "",
      "StreetAddress2": "",
      "City": "Erie",
      "StateOrProvince": "PA",
      "PostalCode": "16502",
      "CountryCode": "US"
    },
    "Contact": null,
    "OriginPortCode": ""
  },
  "Consignee": {
    "Name": "",
    "Address": {
      "StreetAddress1": "",
      "StreetAddress2": "",
      "City": "Carteret",
      "StateOrProvince": "NJ",
      "PostalCode": "07008",
      "CountryCode": "US"
    },
    "Contact": null,
    "DestinationPortCode": "EWR"
  },
  "ShipmentAccessorials": [],
  "OriginAccessorials": [
    "COMMERCIAL_LOCATION"
  ],
  "DestinationAccessorials": [
    "CFS"
  ],
  "RequestingUser": {
    "Name": "Ex Works Support",
    "Phone": "",
    "Email": "support@exworksinc.com"
  },
  "ReferenceNumber": "DFQD:Q00141"
}
