### ISSUE TITLE
[Loggly Sink] Memory Leak

### ISSUE THREAD

**Issue by NiklasArbin** [serilog/serilog#580] opened 2015-11-13 07:17 UTC
Using SeriLog with the LogglySink and wiring it using SimpleInjector LifeStyle.WebApiWebRequest will cause each new sink to hold references to all objects that uses ILogger as dependency and will not be available for GC causing the application to run out of memory.

![](https://slack-files.com/files-tmb/T042LAX8T-F0EDF0S4X-791a60be19/pasted_image_at_2015_11_12_08_38_pm_160.png)

Image showing memory trace after 612 requests being made.

I've temporarily worked around the issue by wiring the ILogger as singleton and manually resolved the per request dependencies.

It is possible that It's a sideeffect of our code, but it's pretty vanilla and I do not have the time right now to submit a complete reproduction of the issue, but it should be pretty easy to spot.

**Comment by NiklasArbin** [comment] 2015-11-13 07:33
I realize that wiring the ILogger per request might be a performance issue, a solution might be to have clear documentation on how Serillog expects to be handled by ioc containers.

**Comment by nblumhardt** [comment] 2015-11-13 10:11
Hi @NiklasArbin - yes, the problem is as you describe - Serilog expects you'll create one root logger and use it throughout. Does registering it as a singleton with your IoC container cover it?

(If your IoC container automatically disposes the loggers it creates I don't think you should see a memory leak - interested to know where the references are if you figure it out.)

There's an example integration between Serilog and Autofac here: https://github.com/nblumhardt/autofac-serilog-integration - not sure if it can be ported to SimpleInjector but I'd guess so. Let me know if this helps.

Cheers,
Nick

**Comment by NiklasArbin** [comment] 2015-11-14 12:32
Registering it as a singleton does solve the problem. Even though I want to investigate some more since I'm seing some references being held that should be disposed. But only single instances are being held so it's not very critical.
The logger was setup to be disposed at the end of each requests which works fine for all other components, but the Loggly SInk was never disposed properly. I have not seen this issue with other Sinks (rolling file/trace).

**Comment by NiklasArbin** [comment] 2015-11-14 12:39
![pasted image at 2015_11_12 08_38 pm](https://cloud.githubusercontent.com/assets/2376888/11163575/1fa6a82c-8ad5-11e5-9b46-d2ce2d78ca4d.png)

**Comment by nblumhardt** [comment] 2015-11-17 21:03
Thanks for the follow-up Niklas. I suspect something's preventing disposal on the app-side, since the Loggly sink is using the same base PeriodicBatchingSink infrastructure that is used in other sinks (and unregisters itself on disposal).

(File/trace sinks don't use batching, and so avoid the issue here.)

I think use of the event handler needs a rethink in 2.0 (it isn't available on all platforms) but in this instance I think we'll close the issue unless more data comes to light suggesting the problem's with the sink itself.

**Closed by nblumhardt** 2015-11-17 21:03 UTC
