### ISSUE TITLE
Logging Parameters Even Though They Are Not In Message

### ISSUE THREAD

**Issue by john-larson** [serilog/serilog#1680] opened 2022-05-24 18:41 UTC
I am using Serilog over the ASP.NET Core ILogger interface. When I do `logger.LogWarning("message", obj1, obj2)`, I expect Serilog to serialize and log the `obj1` and `obj2` objects. But apparently, Serilog only logs these parameters if they are contained in the message template in a way such as  `logger.LogWarning("message, {obj1}, {obj2}", obj1, obj2)`.

There are suggestions on the internet to use `log.ForContext` just to be able to log the parameters. And there are several problems with this. First of all, Microsoft's ILogger does not have ForContext. Second of all, I am not actually trying to create another logger with a different context. I only want the parameters to be logged even though they are not in the message. It is only intuitive that logging of objects occur regardless of the message. 

Is there a valid reason why this restriction exists and it does not work out of the box? I find it very confusing.

**Comment by nblumhardt** [comment] 2022-05-24 21:20
Hi John, thanks for your message; check out https://nblumhardt.com/2016/11/ilogger-beginscope/ for how this is done in MEL through `BeginScope()`.

The current behavior is by design, in your desired syntax there's no way for Serilog to associate names with the `obj1` and `obj2` parameters (whether logging via Serilog or through MEL as shown in your example). Serilog places significant emphasis on producing useful event data.

It's very unlikely any change will be made here, so I'll close this to keep our issue tracker manageable, but if you need any help getting `BeginScope()` to do what you need, please let me know.

**Closed** 2022-05-24 21:20 UTC
Labels: enhancement
