### ISSUE TITLE
Change wiki page of sinks to contain a list to the repositories

### ISSUE THREAD

**Issue by mivano** [serilog/serilog#418] opened 2015-04-01 07:51 UTC
Instead of providing the list we currently have (https://github.com/serilog/serilog/wiki/Provided-Sinks), it might be an idea to have a table which lists all the sinks and their repositories instead. So only provide the documentation for the build in ones, and the rest is document on their corresponding repositories. See also the comment here: https://github.com/serilog/serilog-sinks-elmahio/pull/1/files#r27549436

For the Elasticsearch sink I m already providing more documentation than what would fit on the existing wiki page.

**Comment by nblumhardt** [comment] 2015-04-01 09:24
Strongly agreed - duplicate of #411 :-)

**Closed by nblumhardt** 2015-04-01 09:24 UTC

**Comment by mivano** [comment] 2015-04-01 10:44
Ah sorry about that. Thought it was only for providing the link from repository to main serilog.
