### ISSUE TITLE
Configure Serilog in separate class library instead of API project

### ISSUE THREAD

**Issue by giridharprakash** [serilog/serilog#1430] opened 2020-05-05 13:33 UTC
Environment:
Asp.Net Core 3 API
Mac OS

I created a .Net standard library and I moved the entire Serilog configuration to that library. Now I just referenced class library in API project without adding Serilog packages to API.

Problem: ILogger inside the controller is not logging a message but the message in Program.cs works fine. I understand why it is working in the Program.cs because I am using Serlog's Log.Logger.information() to write a message but the controller is not logging means the dependency injection for ILogger is somewhere broken.

Note: if I eliminate the class library and write the same initialization code in the program.cs and add all Serilog packages in the API project then everything works fine.

I created a sample project and published in Github. API projects can be started and should see a message in console output. https://github.com/giridharprakash/QuicLog

**Comment by nblumhardt** [comment] 2020-05-05 22:52
Duplicate of https://stackoverflow.com/questions/61605375/configure-serilog-in-separate-class-library-instead-of-api-project?stw=2 -followed up there

**Closed by nblumhardt** 2020-05-05 22:52 UTC
Labels: invalid

**Comment by giridharprakash** [comment] 2020-08-01 20:51
@nblumhardt did you get a chance to look at this?

**Comment by shilpask1983** [comment] 2021-01-12 07:25
same issue. was this resolved?

**Comment by ankitlnu** [comment] 2021-07-09 12:38
same issue. was this resolved?
