### ISSUE TITLE
Error on preview 3.0.0.01842

### ISSUE THREAD

**Issue by Teknel** [serilog/serilog#1843] opened 2023-01-31 16:15 UTC
When updating to version 3.0.0-dev-01842 the following error occurs at LoggerConfiguration

CODE
Log.Logger = new LoggerConfiguration().MinimumLevel.Debug()
					.WriteTo.File(CoreData.Storage.FileLogPath, outputTemplate: AppFormat)
					.WriteTo.Seq("http://localhost:5341/")
					.CreateLogger();

ERROR
System.MissingMethodException: 'Method not found: 'Serilog.LoggerConfiguration Serilog.Configuration.LoggerSinkConfiguration.Sink(Serilog.Core.ILogEventSink, Serilog.Events.LogEventLevel)'.'

Returning to version 2.12.1-dev-01635 all works fine again.

Thanks

**Comment by sungam3r** [comment] 2023-01-31 19:05
3.x versions contain breaking changes. It's by design. @SimonCropp began some time ago a series of commits regarding moving main repo from v2.x into v3.x. See top 20-30 commits from here https://github.com/serilog/serilog/pulls?q=is%3Apr+is%3Aclosed+author%3ASimonCropp

**Comment by SimonCropp** [comment] 2023-02-01 01:31
i think we can start updating downstreams. @nblumhardt any objections?

**Comment by nblumhardt** [comment] 2023-02-03 03:34
Interesting! I think the offending line is here:

https://github.com/datalust/serilog-sinks-seq/blob/dev/src/Serilog.Sinks.Seq/SeqLoggerConfigurationExtensions.cs#L135

And can now be simplified to `loggerSinkConfiguration.Sink(sink, restrictedToMinimumLevel, controlledSwitch)`.

Surprised I didn't notice an obsoletion warning there 🤔  - wonder if it'll be common to see breakage around this one?

Could be as good a time as ever to start patching up a few of these :-)

**Comment by nblumhardt** [comment] 2023-02-03 06:01
Hmm, not so much luck; I just checked how the Seq sink uses the overload in question, it's not actually equivalent to what I wrote above (`controlledSwitch` isn't a `LoggingLevelSwitch`).

It could still be fixed by either adding a `null` for the optional `LoggingLevelSwitch` parameter (all versions) or rebuilt against 3.0.0-* (source compatible).

I'll go with the former, and we can find out down the track whether the Seq sink is an outlier here or if we need to bring that overload back :-)

**Comment by nblumhardt** [comment] 2023-03-29 04:55
I'll close this as we're not yet ready to compatibility-test 3.0; when we're closer to done, we'll run through as many public sinks as we can and check for any breakage. Thanks for raising this, though!

**Closed by nblumhardt** 2023-03-29 04:55 UTC
Labels: bug
