### ISSUE TITLE
[Logentries Sink] Never loaded if it's being defined in the appSettings.

### ISSUE THREAD

**Issue by PureKrome** [serilog/serilog#582] opened 2015-11-16 12:52 UTC
Hi all :smile: 

I'm trying to load some sinks via my `appSettings`. Given the following section only the first two (of the three) are loaded:

```
    <add key="serilog:write-to:ColoredConsole" />
    <add key="serilog:write-to:Trace" />
    <add key="serilog:using" value="Serilog.Sinks.Logentries" />
    <add key="serilog:write-to:Logentries" value="f1262c55-snipsnipsnip"/>
```

but .. if i programatically load/write to the Logentries sink, it is loaded!

```
return new LoggerConfiguration()
                .ReadFrom.AppSettings()
                .WriteTo.Logentries("f1262c55-snipsnipsnip")
                .CreateLogger();
```

so it _always_ ignores the info in the appSettings.

Is this an issue with the Sink ? Or how I've tried to set it up in the config file?

**Comment by nblumhardt** [comment] 2015-11-16 21:52
G'day g'day! :-)

The last configuration line should include the parameter name, in this case `token`, so:

```xml
<add key="serilog:write-to:Logentries.token" value="f1262c55-snipsnipsnip"/>
```

Hopefully this fixes it for you, if not please let me know. We've been adding XML configuration samples to our READMEs over time, I'll add this one if everything works as expected.

Cheers,
Nick

**Comment by PureKrome** [comment] 2015-11-16 23:21
Hi @nblumhardt - ok .. so you're saying this is what I should have:

```
 <add key="serilog:write-to:ColoredConsole" />
    <add key="serilog:write-to:Trace" />
    <add key="serilog:using" value="Serilog.Sinks.Logentries" />
    <add key="serilog:write-to:Logentries.token" value="f1262c55-snipsnipsnip"/>
```

also .. why `"serilog:write-to:Logentries.token"` and not `"serilog:write-to:Logentries"` ?

I thought `"serilog:write-to:Logentries"` is the same as `.WriteTo.Logentries` and the `value=...` are anything in the method's parenthesis.

**Comment by nblumhardt** [comment] 2015-11-17 21:29
:+1: LGTM.

Supporting short-hand configuration (without the parameter name) seems nice in this case, but for sinks requiring multiple parameters it's not so clear how they'd be specified using the "terse" syntax.

Let me know how you go; on a mission to clear out the tracker so closing this for now as "by design" :-)

**Closed by nblumhardt** 2015-11-17 21:29 UTC
