### ISSUE TITLE
Watch the config file at runtime

### ISSUE THREAD

**Issue by chucklu** [serilog/serilog#1460] opened 2020-07-14 03:07 UTC
I first file a new issue in project serilog-settings-appsettings, and nobody replies. Then I come here to submit a new issue

**Is your feature request related to a problem? Please describe.**
https://github.com/serilog/serilog-settings-appsettings/issues/44

**Describe the solution you'd like**
when I edit the configuration file at runtime, the setting should be auto reload.

**Comment by nblumhardt** [comment] 2020-07-14 09:15
Duplicate of serilog/serilog-settings-appsettings#44

**Closed by nblumhardt** 2020-07-14 09:15 UTC
Labels: duplicate
