### ISSUE TITLE
ForContext Source Name

### ISSUE THREAD

**Issue by no1melman** [serilog/serilog#1129] opened 2018-03-12 14:36 UTC
Is there a reason why we couldn't just provide the source as a string. I assume this is doing `source.FullName` under the hood. It would be nice just to be able to provide source full name as a single string argument

https://github.com/serilog/serilog/blob/031872f5b369a9eddbcc6bdd7e3f8aa2315f5dde/src/Serilog/Log.cs#L115

**Comment by tsimbalar** [comment] 2018-03-12 15:45
I am closing is as a  
Duplicate of #886

**Comment by no1melman** [comment] 2018-03-13 10:27
Hi thanks for the reply.

I can't see the similarity between Class Name and Property Name. So I don't really see this as a solution.

I was just looking for an overload of just doing `string typeName` alongside `Type source`. I can't find what the code is doing under the hood

**Comment by no1melman** [comment] 2018-03-13 10:30
I read that whole duplicate thread, so I don't expect this thread to go any where.

**Comment by tsimbalar** [comment] 2018-03-13 11:13
@no1melman the convention is that when you use `Log.ForContext<MyClass>()` , it adds to the logged event a property called `SourceContext` containing `TheFull.NameSpace.Of.MyClass` .

If you want to have something else in the property `SourceContext`, you can do it calling  `.ForContext("SourceContext", "Another arbitrary string")`, or possibly add an extension method ... You won't have it in the `static Log` class though, as mentioned in #886 .

This is equivalent to what `Logger.ForContext()` does here : 
https://github.com/serilog/serilog/blob/031872f5b369a9eddbcc6bdd7e3f8aa2315f5dde/src/Serilog/Core/Logger.cs#L168-L191

I'll reopen the issue to make sure I understand your question. Feel free to close it if you have the answer you wanted :)

**Comment by no1melman** [comment] 2018-03-13 11:55
Yeah that's a fair solution!

**Closed** 2018-03-13 11:55 UTC
