### ISSUE TITLE
Async losing context

### ISSUE THREAD

**Issue by nickfr** [serilog/serilog#472] opened 2015-06-18 07:59 UTC
I am losing context in serilog when doing the following
```
    public async Task<byte[]> TestAsync(TestQuery query)
    {
        using (LogContext.PushProperty("CorrelationId", query.CorrelationId))
        {
            var builder = new Foo(this.logger);
            return await builder.DoSomething(query);
        }
    }
```

When I say lose context I mean that if DoSomething continues to log then the early messages have the correlation id and the later ones don't. 

If instead I do the following all is good - i.e. the correlation id appears on all downstream messages.
```
public async Task<byte[]> TestAsync(TestQuery query)
{
    var lgr = this.logger.ForContext("CorrelationId", query.CorrelationId);
    var builder = new Foo(lgr);
    return await builder.DoSomething(query);
}
```

**Comment by nblumhardt** [comment] 2015-06-18 09:19
Thanks for the report, definitely looks like one we need to investigate.

**Comment by nickfr** [comment] 2015-06-18 10:17
You're welcome, and if I can do anything to help let me know.

My actual situation is somewhat more complicated because I'm using
dependency injection - ideally I want to inject the logger but then add a
correlation id into the logger at the start of a service call and have it
used throughout the execution of that call (that call and much of the
cascading calls inside are async).

Using

var lgr = this.logger.ForContext("CorrelationId", query.CorrelationId);

clearly doesn't work with a dependency injection approach - I think your
solution does, although I'm not 100% clear I must admit.

Anyway - I'm loving serilog and seq and if it all goes well during this
trial I will roll it out over the whole project. We are breaking up a large
legacy project into microservices and I'd like the microservices to all log
to a centralised service with correlation and structured data. Serilog and
seq seem ideal for this - and if we can let the support staff use seq to
see what's been going on then we will have a very powerful outcome.

regards

-NiCK

**Comment by nblumhardt** [comment] 2015-06-18 21:56
Hi again,

I've done some testing and can't reproduce this; we have a test in the suite that seems to cover this scenario precisely:

https://github.com/serilog/serilog/blob/dev/test/Serilog.Tests/Context/LogContextTests.cs#L79

I've also duplicated this test to use the `PermitCrossAppDomainCalls` setting.

Is there any chance you can add some more details around how the async method behaves in your scenario? Or, a failing test case would be very much appreciated.

Thanks!
Nick

**Comment by nickfr** [comment] 2015-06-19 08:56
Thanks for helping.

I'm trying to pull out the failing bits into a separate project but as yet it is working correctly (typical!).

It's one of those unpredictable things like a lot of async issues - being logging at least I still have the traces so I know where it went wrong but it happens after a number of iterations somewhat deep in, when suddenly a line of code that on a previous iteration had a correlation id now doesn't.

I'll let you know if I can get something tangible.

**Comment by nblumhardt** [comment] 2015-06-23 22:04
Thanks Nick; I'll close this for the time being but if you manage a repro it'd be much appreciated if you can reopen it. Cheers!

**Comment by nickfr** [comment] 2015-06-24 09:53
I understand. It is frustrating me because I am definitely still having the
issue in my real code but if I can't repro then you can't fix it.

**Comment by IanYates** [comment] 2015-06-24 12:44
@nickfr - Are you on .NET v4 or v4.5?  If you're on .NET 4 could you be running in to the problems described at http://nblumhardt.com/2013/09/serilog-gets-a-diagnostic-context/, which links to http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html for all the gory details.

I had some time this evening so I write what I thought would be a horrible test case to reproduce this, by starting some nested tasks, which themselves started some tasks that weren't awaited and kept logging after the using statement block had finished and that all worked fine.  Then I dropped back to .NET 4, expecting to run into the problems outlined, and didn't, but that may be because I didn't interleave LogContexts enough (I only had one outer log context).  Maybe your code is more complex and hits the described issues (assuming you're on .NET 4 of course)

**Comment by nickfr** [comment] 2015-06-24 14:17
I'm on 4.5. I only have an outer LogContext at the entry of the WCF
call then I descend through various async calls and then always in the same
place one method logs the correlation id and a nested asynchronous method
(in the same object) doesn't.

I've tried building a sample app to be the same shape and failed to
reproduce. I guess the next step would be to take my real app and cut it
down bit by bit until it starts working. but that will take time to do.

-NiCK

**Comment by hiscodeness** [comment] 2015-08-13 12:56
I'm encountering this issue in a .NET 4.5 NancyFx project. I tried making a reproducable, but the simple test project didn't exhibit the problem. I'll later try to find differences between my main project and the reproducable.

**Comment by hiscodeness** [comment] 2015-08-13 19:28
I managed to create a reproducable based on my real application. Here it is: https://github.com/hiscodeness/SerilogLogContextBug

When you run the application, LogContext is not applied when in the controller (PingModule):
```
<SerilogLogContextBug.LoggingMiddleware> [80000149-0007-fd00-b63f-84710c7967bb] Begin HTTP request http://localhost:63141/
<SerilogLogContextBug.PingModule>        [] Pinged!
<SerilogLogContextBug.LoggingMiddleware> [80000149-0007-fd00-b63f-84710c7967bb] End HTTP request http://localhost:63141/
```

The problem can be fixed by commenting this line:
https://github.com/hiscodeness/SerilogLogContextBug/blob/master/SerilogLogContextBug/Startup.cs#L39

after which the output is correct:
```
<SerilogLogContextBug.LoggingMiddleware> [80000a8a-0006-fd00-b63f-84710c7967bb] Begin HTTP request http://localhost:63141/
<SerilogLogContextBug.PingModule>        [80000a8a-0006-fd00-b63f-84710c7967bb] Pinged!
<SerilogLogContextBug.LoggingMiddleware> [80000a8a-0006-fd00-b63f-84710c7967bb] End HTTP request http://localhost:63141/
```

I didn't investigate in detail what the OWIN middleware in question does, but in my real app I must have that enabled for JWT token security.

**Comment by IanYates** [comment] 2015-08-14 00:41
Perhaps that middleware is not using async/await properly, or it's starting up a task and awaiting it, but specifically instructing the task to not inherit context (the correct terminology escapes me at the moment).

I know what JWT tokens are but haven't had to use them in anger.  Is the JWT package open source?  If not, can you perhaps decompile and inspect it to see what it's up to.

**Comment by hiscodeness** [comment] 2015-08-14 06:03
The middleware is from Microsoft but luckily is open source: https://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security/

I had a quick look at the source code but didn't find anything related to this issue so far. [This bit of code](https://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security/Infrastructure/AuthenticationMiddleware.cs) is what I believe is actually run by the OWIN middleware during a request. 
```
public override async Task Invoke(IOwinContext context)
{
    AuthenticationHandler<TOptions> handler = CreateHandler();
    await handler.Initialize(Options, context);
    if (!await handler.InvokeAsync())
    {
        await Next.Invoke(context);
    }
    await handler.TeardownAsync();
}
```
It is possible to write my own token authentication middleware, but as this is a security concern, I'd rather not do it myself.

**Comment by hiscodeness** [comment] 2015-08-14 07:31
I debugged the reproducable with decompiled assemblies and my issue is not due to the JWT middleware itself, it is related to the interplay between the middleware and how it is run on top of System.Web OWIN hosting. In there, some good old `Begin/End IAsyncResult` stuff goes on that I can't get a good handle on. When I ran the exact same pipeline from a console host, it works just fine (code included in the reproducable).

Anyway, the conclusion seems to be that in my case the problem is OWIN pipeline handling in System.Web causing a 'context switch', not a bug with Serilog.

**Comment by hiscodeness** [comment] 2015-08-14 07:33
I would love a workaround though, other than simply applying the LogContext property a second time later in the pipeline...

**Comment by nblumhardt** [comment] 2015-08-14 22:02
Fantastic - great to finally have some data on this. I agree it's unlikely to be a Serilog problem at this point.

It may be possible to sneak the data across the pipeline somehow using something akin to `HttpContext.Items`, but some experimentation's going to be necessary :-)

Other workarounds/suggestions would be very welcome, but I'll close this issue to keep things tidy here on the tracker.

Thanks everyone for the input on this!

**Closed by nblumhardt** 2015-08-14 22:02 UTC
Labels: core

**Comment by suddenelfilio** [comment] 2015-10-14 11:10
@hiscodeness  Ok I have workaround:

change the order of the use methods and your context will come through:

```cs

app.UseJwtBearerAuthentication(CreateJwtBearerAuthOptions());
app.Use<LoggingMiddleware>();
// Commenting the next line will fix the issue.
app.UseNancy();
```

**Comment by jakubkwa** [comment] 2017-07-28 11:31
Hello all,

I think we've run into an issue related to this one lately and would like to share some thoughts.

**The problem**

In our work environment we have a bunch of Web API applications. In one of them, a very simple one, we decided to do request authentication straight in the controller itself (not handler or anything like that) - well in a collaborator, which is called from the controller to be precise. We also have decorated this collaborator call with another one, which is responsible for adding an access token, upon which we authenticate, to the Serilog `LogContext` using the `PushProperty` method. We thought that using `LogContext` there would be nice, because we can add the value where we extract it and it will just be there if we log something, right? Well, not entirely :) We discovered the problem, when an exception was thrown somewhere in further Controller code (so after adding to the `LogContext`) - this exception should be handled by our custom `ExceptionHandler` implementation and logged in our custom `ExceptionLogger` (these are both pretty standard Web API services). So in `ExceptionLogger` we called the Serilog `ILogger`, but the `LogEvent` did not contain the access token added to the `LogContext` in the controller.

**The investigation**

Now, we were not entirely sure if this was Serilog issue, our issue, Web API issue, so we started to google around and peek in the source code of Serilog and Web API a bit. The fact is that Serilog documentation provides only usages of `LogContext.PushProperty` in a `using` clause, in which this should work with no problems. So maybe the problem is that we wanted to use it in a more sophisticated way - calling the `PushProperty` method in the controller stack and disposing until the request is disposed. However logging an exception in Web API `ExceptionLogger` with all the information gathered previously in Handlers or Controllers doesn't seem like a very odd scenario, does it? :)

So what we know after some investigation:
* Serilog `LogContext` uses `CallContext` `LogicalSetData` and `LogicalGetData` methods under the hood.
* `CallContext`, according to the documentation, is a "specialized collection object similar to a Thread Local Storage for method calls and provides data slots that are unique to each logical thread of execution. The slots are not shared across call contexts on other logical threads. Objects can be added to the CallContext as it travels down and back up the execution code path, and examined by various objects along the path." And this is true for synchronous calls - as can be seen below in the reproduction section.
* For asynchronous calls using `CallContext` will be problematic - it looks like the values are copied over when invoking a method, so you can get, read and use values added in the specific class in its collaborators, but not the other way around - as also can be seen in the reproduction section.
* In a Web API case we have a lot of async/await calls under the hood, even if we don't use them that much ourselves (so even if we have synchronous methods in controllers). This means, that `CallContext` in a scenario like that is not a way to go at all.

**The reproduction**

I've written a couple of tests using Serilog `LogContext` to showcase various scenarios, but this can be done easily the same with `CallContext` directly. Anyway, I've created a simple Serilog sink to actually capture the log event that was passed.

```csharp
  public class LogEventCache
  {
    public LogEvent LogEvent { get; set; }
  }

  public class LogEventCacheSink : ILogEventSink
  {
    private readonly LogEventCache _cache;
    
    public LogEventCacheSink(LogEventCache cache)
    {
      _cache = cache;
    }

    public void Emit(LogEvent logEvent)
    {
      _cache.LogEvent = logEvent;
    }
  }
```
I've also created two classes only for testing purposes - the names are a bit Web API inspired :) So I have a `Controller` class with two methods - one adding a property to `LogContext` only, and one adding a property and actually logging. I also add the property to a collection, to make sure it won't be disposed nor garbage collected.
```csharp
  public class Controller
  {
    private readonly ILogger _logger;
    private readonly List<IDisposable> _properties = new List<IDisposable>();

    public Controller(ILogger logger)
    {
      _logger = logger;
    }

    public void AddToContext()
    {
      _properties.Add(LogContext.PushProperty("Controller", "Value"));
    }

    public void AddToContextAndLog()
    {
      _properties.Add(LogContext.PushProperty("Controller", "Value"));

      _logger.Information("Message");
    }
  }
``` 
And I have a similar `Handler` class, that can either only add a property (and then asks the `Controller` to log) or add a property and log (in this case it asks `Controller` only to add its own property).
```csharp
  public class Handler
  {
    private readonly ILogger _logger;
    private readonly Controller _controller;
    private readonly List<IDisposable> _properties = new List<IDisposable>();

    public Handler(ILogger logger, Controller controller)
    {
      _logger = logger;
      _controller = controller;
    }

    public void AddToContextAndCallControllerWithLog()
    {
      _properties.Add(LogContext.PushProperty("Handler", "Value"));
      
      _controller.AddToContextAndLog();
    }

    public void AddToContextAndCallControllerAndLog()
    {
      _properties.Add(LogContext.PushProperty("Handler", "Value"));

      _controller.AddToContext();

      _logger.Information("Message");
    }
  }
```
Now this is how this behaves in a synchronous world:
```csharp
  [TestFixture]
  public class SerilogLogContextUnitTests
  {
    private ILogger _logger;
    private LogEventCache _cache;
    private Handler _handler;
    private Controller _controller;

    [SetUp]
    public void SetUp()
    {
      _cache = new LogEventCache();

      _logger = new LoggerConfiguration()
        .Enrich.FromLogContext()
        .WriteTo.Sink(new LogEventCacheSink(_cache))
        .CreateLogger();

      _controller = new Controller(_logger);
      _handler = new Handler(_logger, _controller);
    }

    [Test]
    public void WhenValueIsAddedToTheContextInTheLoggingMethod_ShouldValueBeAccessibleInLogEvent()
    {
      _controller.AddToContextAndLog();

      AssertPropertyValue("Controller", "Value");
    }

    [Test]
    public void WhenValueIsAddedToTheContextInTheMethodCallingTheLoggingMethod_ShouldValueBeAccessibleInLogEvent()
    {
      _handler.AddToContextAndCallControllerWithLog();

      AssertPropertyValue("Handler", "Value");
    }

    [Test]
    public void WhenValueIsAddedToTheContextInTheMethodCalledFromTheLoggingMethod_ShouldValueBeAccessibleInLogEvent()
    {
      _handler.AddToContextAndCallControllerAndLog();

      AssertPropertyValue("Controller", "Value");
    }

    private void AssertPropertyValue(string propertyName, string propertyValue)
    {
      Assert.AreEqual((_cache.LogEvent.Properties[propertyName] as ScalarValue).Value, propertyValue);
    }
  }
```
All this tests are passing. So:
* If I add a property to `LogContext` in the `Controller` and log there, it will be okay.
* If I add a property to `LogContext` in the `Handler` and call the `Controller` to log, it will be okay.
* If I add a property to `LogContext` in the `Controller` and log in the `Handler` after that, it will be okay.

Now this looks pretty straightforward, however it changes when we get to introduce asynchronous stuff. So my `Controller` and `Handler` now look like this:
```csharp
  public class Handler
  {
    private readonly ILogger _logger;
    private readonly Controller _controller;
    private readonly List<IDisposable> _properties = new List<IDisposable>();

    public Handler(ILogger logger, Controller controller)
    {
      _logger = logger;
      _controller = controller;
    }

    public async Task AddToContextAndCallControllerWithLogAsync()
    {
      _properties.Add(LogContext.PushProperty("Handler", "Value"));

      await _controller.AddToContextAndLogAsync();
    }

    public async Task AddToContextAndCallControllerAndLogAsync()
    {
      _properties.Add(LogContext.PushProperty("Handler", "Value"));

      await _controller.AddToContextAsync();

      _logger.Information("Message");
    }
  }

  public class Controller
  {
    private readonly ILogger _logger;
    private readonly List<IDisposable> _properties = new List<IDisposable>();

    public Controller(ILogger logger)
    {
      _logger = logger;
    }

    public async Task AddToContextAsync()
    {
      _properties.Add(LogContext.PushProperty("Controller", "Value"));

      await Task.Delay(10);
    }

    public async Task AddToContextAndLogAsync()
    {
      _properties.Add(LogContext.PushProperty("Controller", "Value"));

      await Task.Delay(10);

      _logger.Information("Message");
    }
  }
```
And the tests:
```csharp
  [TestFixture]
  public class SerilogLogContextUnitTests
  {
    private ILogger _logger;
    private LogEventCache _cache;
    private Handler _handler;
    private Controller _controller;

    [SetUp]
    public void SetUp()
    {
      _cache = new LogEventCache();

      _logger = new LoggerConfiguration()
        .Enrich.FromLogContext()
        .WriteTo.Sink(new LogEventCacheSink(_cache))
        .CreateLogger();

      _controller = new Controller(_logger);
      _handler = new Handler(_logger, _controller);
    }

    [Test]
    public void WhenValueIsAddedToTheContextInTheLoggingMethod_ShouldValueBeAccessibleInLogEvent()
    {
      _controller.AddToContextAndLogAsync().Wait();

      AssertPropertyValue("Controller", "Value");
    }

    [Test]
    public void WhenValueIsAddedToTheContextInTheMethodCallingTheLoggingMethod_ShouldValueBeAccessibleInLogEvent()
    {
      _handler.AddToContextAndCallControllerWithLogAsync().Wait();

      AssertPropertyValue("Handler", "Value");
    }

    [Test]
    public void WhenValueIsAddedToTheContextInTheMethodCalledFromTheLoggingMethod_ShouldValueBeAccessibleInLogEvent()
    {
      _handler.AddToContextAndCallControllerAndLogAsync().Wait();

      AssertPropertyValue("Controller", "Value");
    }

    private void AssertPropertyValue(string propertyName, string propertyValue)
    {
      Assert.AreEqual((_cache.LogEvent.Properties[propertyName] as ScalarValue).Value, propertyValue);
    }
  }
```
The output of this tests is that the third one is failing. So:
* If I add a property to `LogContext` in the `Controller` and log there, it will be okay. This shows, that the `CallContext` is preserved after the awaited call.
* If I add a property to `LogContext` in the `Handler` and call the `Controller` to log, it will be okay. This shows, that the `CallContext` is copied over to the next method call, just as in synchronous scenario.
* If I add a property to `LogContext` in the `Controller` and log in the `Handler` after that, it will fail. This shows, that the `CallContext` is not copied over on the way back - in the `Handler` you get just those values, which you had already before the await (something similar can be found in async/await best practices https://msdn.microsoft.com/en-us/magazine/jj991977.aspx - "by default, when an incomplete Task is awaited, the current 'context' is captured and used to resume the method when the Task completes.").

**The solution or workaround**

Not sure if what we did for now is a solution or workaround, but we decided to basically use the `LogContext.PushProperty` method as it is in the documentation. So we limit ourselves not to add values to `LogContext` anywhere in the app, but just before the `ILogger` call. This guarantees, that the values will be there. Of course in our scenario this means, that we need to provide the access token somehow to the class responsible for making the logging call, but this is something we can do in various ways, all of them probably connected to using `HttpContext.Current` - we can either extract it directly from the `HttpContext.Current.Request` headers, or still have a decorator extracting the token and putting it in `HttpContext.Current.Items` in one place and then take it from there just before the logging call, to put it in `LogContext`.

This works for us right now, and I'm not sure if anything can be done on Serilog side to avoid problems like that. In this very scenario using `HttpContext` instead of `CallContext` would work, but that's probably not something you'd like to include in the codebase just like that. But maybe in a separate package for Web? Or maybe give a chance to choose somehow in the configuration the storage for `LogContext` properties? Thinking loudly here, but with Web API being still relatively popular, and used along with a custom global `ExceptionHandler` and/or `ExceptionLogger` it might be a cause of problems for at least some people, like it was for us :)

PS We've also investigated how log4net handles stuff like that. There are 3 types of contexts you can add properties to in log4net - none of them would support a scenario like we had. There is a `GlobalContext` which is preserved all the time, `ThreadLogicalContext` which also relies on `CallContext` so will behave in a similar way and `ThreadContext`, which is connected to current managed thread, so will have it's own problems in ASP .NET application.

**Comment by nblumhardt** [comment] 2017-07-28 21:07
@jakubkwa thanks for sharing your experiences. That's a bit of a monster comment to digest :-) ... if there's a specific enhancement you'd like to suggest, a separate/brief issue or PR may be quicker to get feedback on.

One thing to look out for, if you're not using `using` with `LogContext`, make sure you still preserve the correct "pop" order - behaviour should be sane but won't be intuitive if you pop a parent frame before its children. HTH!

**Comment by jakubkwa** [comment] 2017-07-31 12:47
@nblumhardt I know it's been a long one, however I hope it will be useful for others facing similar problems :)

I'd like to create a separate issue, however I'm not sure how to categorize it - whether this is a bug or an enhancement to make. And I'm also not sure if a solution won't require a separate package - is it okay to post int Serilog issues even if so?

**Comment by nblumhardt** [comment] 2017-07-31 22:05
@jakubkwa I'm not sure either, but it's fine to post to this tracker. If you can boil it down to:

 1. Short code snippet in question
 2. Current behavior
 3. Desired behavior

we can figure it out from there :-)

Best not to make too many assumptions about the underlying implementation, as this varies depending on the platform today. Unless you're on .NET 4.5 I think `LogContext` is driven by `AsyncLocal<T>`, not `LogicalCallContext`. Starting at the behavioral level should be enough to get us off in the right direction. Thanks!

**Comment by ffMathy** [comment] 2018-04-22 11:50
Couldn't we use this class to get around this problem?

https://msdn.microsoft.com/en-us/library/dn906268(v=vs.110).aspx

**Comment by oliverjanik** [comment] 2019-10-24 07:19
For me this happens after OAuthBearerAuthenticationMiddleware runs in the OWIN pipeline and my current version of Serilog uses AsyncLocal.
