### ISSUE TITLE
custom current timestamp

### ISSUE THREAD

**Issue by zelyony** [serilog/serilog#1950] opened 2023-09-06 08:09 UTC
Issue is not about timestamp format but about timestamp itself!

For [backtesting](https://en.wikipedia.org/wiki/Backtesting) of trading strategy you running it on history market data.
So "current time" for backtesting is taken history time - sorted event tick time.

NB this time is discrete: 09:00:00.356, 09:00:00.361 etc depends on events that exists in history market data.

And is necessary to see log events tied to historical data and no matter what time of day you run those tests.

So there must be a way to tell Serilog where to take the current timestamp. For example:
```
interface ITimeService { 
  DateTimeOffset Timestamp { get; } 
}
```
that can be set with config (```<TimeService>"(implementation)Type, Assembly"</TimeService>```) or by using DI.

**Comment by nblumhardt** [comment] 2023-09-07 01:36
This is a duplicate of #1920 👍

**Closed by nblumhardt** 2023-09-07 01:36 UTC
Labels: duplicate
