### ISSUE TITLE
"Collection was modified; enumeration operation may not execute" with complex enricher chain

### ISSUE THREAD

**Issue by bartelink** [serilog/serilog#1154] opened 2018-04-29 14:41 UTC
I'm using the dev version of Async and latest of File, Console and Core and got the following exception:

```
2018-04-27 14:21:57.3356+1 FTL HealthLogger Serilog SelfLog warning 2018-04-27T13:21:57.3301713Z Serilog.Sinks.Async.BackgroundWorkerSink fatal error in worker thread: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Serilog.Events.LogEvent..ctor(DateTimeOffset timestamp, LogEventLevel level, Exception exception, MessageTemplate messageTemplate, IEnumerable`1 properties)
   at Serilog.Core.Sinks.SecondaryLoggerSink.Emit(LogEvent logEvent)
   at Serilog.Sinks.Async.BackgroundWorkerSink.Pump() {}
```

Here is an outline of the logger pipeline that triggers it:

```
 new Serilog.LoggerConfiguration()
                .Enrich.WithThreadId()
                .Enrich.FromLogContext()
                .WriteTo.Async(
                    bufferSize: 16384,
                    configure: (Serilog.Configuration.LoggerSinkConfiguration a) =>
                    {
                        if (consoleMinLevel != null)
                            a.Sink(AppHostHealthMonitor.LogSink, restrictedToMinimumLevel: consoleMinLevel.Value);
                        foreach (var filePath in textLogs ?? Enumerable.Empty<string>())
                            a.Logger(l => l
                                .Filter.ByExcluding(x => x.Level >= Serilog.Events.LogEventLevel.Fatal && consoleMinLevel == null)
                                .Enrich.With<UtcTimestampEnricher>()
                                .WriteTo.File(path: filePath, buffered: true, flushToDiskInterval: TimeSpan.FromSeconds(1),
                                    outputTemplate: "{UtcTimestamp:yyyy-MM-dd HH:mm:ss.ffff}|{NLogLevel}|{SourceContext}|{Message:l}|{Properties}{NewLine}{Exception}",
                                    rollOnFileSizeLimit: true, fileSizeLimitBytes: 1024L * 1024 * 20, retainedFileCountLimit: 10));
                    });
```

The problem seems rooted in the following not doing a full deep copy:

```
public void Emit(LogEvent logEvent)
        {
            if (logEvent == null) throw new ArgumentNullException(nameof(logEvent));

            var copy = new LogEvent(
                logEvent.Timestamp,
                logEvent.Level,
                logEvent.Exception,
                logEvent.MessageTemplate,
                logEvent.Properties.Select(p => new LogEventProperty(p.Key, p.Value)));

            _logger.Write(copy);
        }
```

Obviously 'just' materializing is going to cost perf... (there is no major perf win to splitting the enrich into the async pipeline - its more that logically those enrichers are only useful there and I have other sinks that do not require the same enrichment which are paying the price for something that I was trying to offload)

If anyone can give me some guidance as to what the intended semantics are, I'm happy to fix it appropriately.

**Comment by bartelink** [comment] 2018-04-29 22:06
Seeing this (thread death) pretty consistently on multiple boxes.
- Moving back to `master` 1.1 Async seems to make the problem go away (and have not had it in prod over multiple weeks).
- I also tried NuGet package `https://www.nuget.org/packages/Serilog.Sinks.Async/1.2.0-dev-00018`, which does not make the problem go away either.
- Apply "doctor it hurts when I do this" logic and putting all the enrichers outside the async seems to reduce how long it takes for the condition to arise, but does not prevent it.

🤔 My wild guess is that the switch to `GetConsumingEnumerable` in the post 1.1 work before mine, makes this race condition dramatically more likely to occur.

**Comment by nblumhardt** [comment] 2018-04-29 22:27
Interesting... think I'll need some time to trawl through it. The deep copy shouldn't be needed because the `LogEventPropertyValue` subclasses are immutable.

Is `AppHostHealthMonitor.LogSink` doing anything asynchronous?

**Comment by bartelink** [comment] 2018-04-29 22:34
Seems key diff between dev and master is that`master` is using Logger.Write whereas dev is using `ILogSink.Emit`
This is reproable independent of the health monitoring (I removed it at the same time as I consolidated the enrichers outside the pipe)

**Comment by bartelink** [comment] 2018-04-29 22:53
I see now I was misunderstanding some copy not being deep enough (I had incorrectly inferred the LogEvent had an IEnumerable that in some cases was not materialized vs a Dictionary under its control).
🤔 It does seem looking more closely that it has to be an open and shut case of something enriching/touching the source dictionary at the same time as the SecondaryLogger inside the Async is copying it.

**Comment by bartelink** [comment] 2018-05-02 11:35
Determined that this was a PEBKAC issue relating to what I was doing inside the `.Async`'s `configure` - see the gitter. Will document as I close when we reach root cause. For now, the issue was that I was doing a `.WriteTo` a `.Sink` that did enrichment as well as a `a.Logger`. i.e. the `a.Sink` seems to be be triggering enrichment overlapping with enrichment in the `.Logger`. The mitigation is to wrap the logging in a `.Logger`, which ensures the two loggers within the `.Async` never touch the original (I `.WriteTo.Seq` after the `.WriteTo.Async` and that works fine too - the conflict is confined to inside the `.Async` above):

Mitigated version:

```
                        // NB don't assume that these logger chains are processed sequentially
                        if (consoleMinLevel != null)
                            // NB need to ensure messages get cloned to an independent copy by the `.Logger` or the main `a.Logger` can throw an
                            // InvalidOperationException due to the mutations that AppHostHealthMonitor.LogSink's Enrichers trigger
                            a.Logger(
                                l => l.WriteTo.Sink(AppHostHealthMonitor.LogSink),
                                restrictedToMinimumLevel: consoleMinLevel.Value);
```

**Comment by nblumhardt** [comment] 2018-05-09 22:35
Just to summarize where I think this landed..

 * Serilog's `LogEvent` is not thread-safe for readers concurrent with writers; concurrent reads are fine, but only in the absence of writes
 * Serilog makes this work by following two rules:
   - In the Serilog pipeline, modifications are only permitted during enrichment, which happens synchronously before the event is passed to any (potentially-asynchronous) sinks
   - If an event needs to be "modified" other than during enrichment, a copy is made and the copy is passed on to be modified instead (you can see this in action in `SecondaryLoggerSink`); this avoids modifying the original event, which may already be being processed asynchronously by other components
 * Loggers can mutate the events passed into them via `Write(event)`, and so events emitted by one logger must be copied before calling this method (i.e. as per `SecondaryLoggerSink`)
 * The code in question passes events into a secondary logger without doing this

(Really all of this boils down to a simple rule: modify events in enrichers, don't modify events in sinks.)

Because the app and pipeline are quite complex, it's difficult to offer a more precise analysis here, but, breaking the rule will result in the kind of exception that's being reported, and removing the offending code (or working around it by relying on `WriteTo.Logger()`'s implicit copy) does cause the issue to disappear, so I'd say we're as close to conclusive as possible at this point.

There are heaps of opportunities to design more bullet-proof pipelines based on immutable events (I've been working on one for a year or so on the sidelines..) but getting performance and allocation overhead competitive with the current design is a decent challenge. I think we should close this issue now, but keep an eye on future opportunities.

**Comment by bartelink** [comment] 2018-05-09 22:49
Thanks for laying it out in detail; this should hopefully help anyone else that ever manages to tie themselves up in knots to the degree I inadvertently did.

>Loggers can mutate the events passed into them via Write(event), and so events emitted by one logger must be copied before calling this method (i.e. as per SecondaryLoggerSink)

The DSL appearing to allow the chaining of `WriteTo.X` confused me about this being an obviously safe thing. i.e. IIRC `WriteTo.File().WriteTo.Seq()` works. But I could be wrong....

Happy to close - and definitely appreciate making immutable pipelines efficient is not as trivial as it sounds.

**Comment by skomis-mm** [comment] 2018-05-10 10:45
@bartelink I checked this and found the regression I made in the this [pr](https://github.com/serilog/serilog-sinks-async/pull/19).
The underlying reason is described by @nblumhardt that loggers can mutate the events passed into them via Write(event) in different threads.
But another issue is that the current `.Wrap` is not working (at least for the `Async` package) as expected for pipelines built with the `Action<LoggerSinkConfiguration> configure` action. It doesn't create an aggregating sink and adds wrapped inner sinks to the flat list of the parent logger. Another thing is that the way of how inner pipeline is configured makes difference on the result pipeline:

```
a.Sink(..);
a.Logger(..);
``` 
and
```
a.Sink(..).WriteTo.Logger(..);
```
will create different results.

For the current `Async` implementation the first version will create two `BackgroundWorkerSink`s. So the threading issue is become apparent.
That's why reverting to 1.1 will hide the problem away. It still exists and the following setup won't work for the exact underlying reason
```
Log.Logger = new LoggerConfiguration()
   .WriteTo.Async(c => c.Sink(new LoggerConfiguration().Enrich.WithProperty(...).WriteTo.Sink(...).CreateLogger())
   .WriteTo.Async(c => c.Sink(new LoggerConfiguration().Enrich.WithProperty(...).WriteTo.Sink(...).CreateLogger()))
         .CreateLogger();
```

Summarizing this I beleive aforementioned `pr` should be reverted asap (since 1.2 is on the master already).
Also, `.Async` extension could be modified as well and based on `SecondaryLoggerSink`(`.Logger(...)`) so each inner pipeline will work with their own copy of the event. It will solve the threading issue but still not ideal (inner sinks will observe enriched events as side effects because of mutability)

Thoughts?

**Comment by bartelink** [comment] 2018-05-10 11:00
Hm, sounds very possible. We're using the dev NuGet and your post reminds me that a guy on our team was seeing very strange behavior (which I've not had time to dig into - it only came to light around the same time as Nick's post) where (using non-chained building) a `.Filter.ByExcluding` is not being applied (I have 2x `.Logger`s nested within the `.Async`).

I guess the first step on this is a failing test; unfortunately I won't personally have time to inline that into my day...

**Comment by nblumhardt** [comment] 2018-05-10 23:53
Thanks for the analysis, @skomis-mm.

So, taking another perspective, the real weakness here is the method chaining enabled by `WriteTo`, is dangerous, i.e. so that the following apparently innocuous code is allowed:

```
WriteTo.Async(wt => wt.Sink().Enrich...
//                             ^ enrichment is not valid here!
```

Making the suggested change to revert `Wrap()` will mitigate this in some cases, but as you point out, it just moves the problem around. One of the goals of `Wrap()` was to avoid event copying, so ideally we'll be able to avoid `SecondaryLoggerSink`.

One alternative might be to avoid passing the outer logger configuration through here:

https://github.com/serilog/serilog/blob/dev/src/Serilog/Configuration/LoggerSinkConfiguration.cs#L222

We could then reliably prevent calls to `Enrich` having any effect - the added enrichers would just disappear into the aether (or we could detect the issue and throw/warn via `SelfLog`).

Any thoughts?

**Comment by skomis-mm** [comment] 2018-05-11 07:10
@nblumhardt I think it's a bit different. The problem with the `Wrap` is that `1.2.0` can create different pipelines depending on how you configure:

```
                   ̶  BackgroundWorkerSink -> WrappedSink1
                  /
SafeAggregateSink  ̶̶  BackgroundWorkerSink -> WrappedSink2
                  \
                   ̶  BackgroundWorkerSink -> WrappedSink3
```
or 
```
                   ̶  BackgroundWorkerSink -> WrappedSink1
                  /
SafeAggregateSink  ̶̶  WrappedSink2
                  \
                   ̶  WrappedSink2
```
etc.
To make it usable with `Async` it should create this:
```
                                                                ̶  WrappedSink1
                                                               /
SafeAggregateSink -> BackgroundWorkerSink -> SafeAggregateSink ̶ ̶  WrappedSink2
                                                               \
                                                                ̶  WrappedSink3
```

The `1.0-1.1` create this pipeline:
```
                                                                          ̶  WrappedSink1
                                                                         /
SafeAggregateSink -> BackgroundWorkerSink -> Logger -> SafeAggregateSink ̶ ̶  WrappedSink2
                                                                         \
                                                                          ̶  WrappedSink3
```
There is no `SecondaryLoggerSink` and no `LogEvent` copying. So the _lightweightness_ of using `Wrap` is pretty symbolic in this case. 


Just prohibiting
```
WriteTo.Async(wt => wt.Sink().Enrich...
//                             ^ enrichment is not valid here!
```
won't work in the below scenario anyway. It doesn't work for `1.0-1.2` already:
```
Log.Logger = new LoggerConfiguration()
   .WriteTo.Async(c => c.Sink(new LoggerConfiguration().Enrich.WithProperty(...).WriteTo.Sink(...).CreateLogger())
   .WriteTo.Async(c => c.Sink(new LoggerConfiguration().Enrich.WithProperty(...).WriteTo.Sink(...).CreateLogger()))
         .CreateLogger();
```
So on the contrary, adding defensive copy (or make it based on `.Logger(..)`) _will_ fix this. And it looks natural since the pipeline is asynchronous.

**Comment by nblumhardt** [comment] 2018-05-12 04:55
Thanks for digging into it, @skomis-mm - I think I'm on the same page. I'm splitting time between a few too many projects at the moment, and context-switching back into this five minutes at a time is getting tough :-) I'll put aside some time to properly think through the solutions and get a proper reply back onto this thread ASAP.

**Comment by nblumhardt** [comment] 2018-05-13 09:38
Hope you all had a good weekend. I've taken another look and put together #1165, which ensures we reliably get either:

```
                                                                ̶  WrappedSink1
                                                               /
SafeAggregateSink -> BackgroundWorkerSink -> SafeAggregateSink ̶ ̶  WrappedSink2
                                                               \
                                                                ̶  WrappedSink3
```

Or:

```
SafeAggregateSink -> BackgroundWorkerSink -> WrappedSink1
```

depending on the number of sinks inside the wrapper.

The PR also disables `Enrich` etc. within the wrapped configuration block, so `wt.X().Enrich(...)` becomes benign.

I think we're better off trying to make `Wrap()` safe and predictable, rather than falling back on `SecondaryLoggerSink`, to avoid the allocation cost of a defensive copy.

With the PR'd changes, wrapped sinks won't be any more dangerous than custom sinks based on `PeriodicBatchingSink`, which also see "frozen" events that can't be safely mutated.

If we accept #1165 I think we can close https://github.com/serilog/serilog-sinks-async/pull/32. Think I'm on track?

**Comment by skomis-mm** [comment] 2018-05-13 12:17
I think there is still some misunderstanding. Failing back to 1.0-1.1 do not add `SecondaryLoggerSink`. 
Current proposed changes in general is good for a `Wrap` extension (as a standalone fix) but won't do much value for `Async` method (in terms of perf and allocations) and still will hide the threading issue, not really fixing it.

**Comment by nblumhardt** [comment] 2018-05-13 22:25
Sorry @skomis-mm, my comment about `SecondaryLoggerSink` was referring to:

> So on the contrary, adding defensive copy (or make it based on .Logger(..)) will fix threading issue.

(Which would use `SecondaryLoggerSink` under the covers.)

> still hides the threading issue

I guess the difference in perspective might be whether there's actually a threading issue here, or not. From a concurrency standpoint, `Async` is no different from `PeriodicBatchingSink` or any other asynchronous sink - it's just that the API (and broken implementation) of `Wrap()`, and the subtle potentially-mutating behavior of `Logger.Write()`, make it particularly easy to shoot oneself in the foot :-)

If we mitigate the `Wrap()` issues with #1165, I think it mostly leaves the case of using `Logger.Write()` as the major remaining footgun. That one has always been present - guiding people towards chaining in `WriteTo.Logger()`  - rather than writing a sink that forwards events on to a logger - seems like reasonable defense.

Just to make sure we're completely on the same page, with #1165 in (which I think needs to go in anyway, to address the major issues you spotted earlier on), do you still think it's worth trying to improve `Async()` to make it safer, and can we do that without imposing the copying overhead? Thanks!

**Comment by bartelink** [comment] 2018-05-14 09:11
This is looking good, thanks for doing this.
The `WriteTo` semantic change is pretty important - it hadn't even occurred to me that there could be a difference as I was reasoning (based solely off the fact that the return value was not being used/required and not thinking too deeply about what might happen otherwise), that it didn't matter.
Finally, I'm wondering is there perhaps a clean way to make the `.Enrich` `SelfLog` if it's in an inappropriate place rather than silently failing ?

**Comment by nblumhardt** [comment] 2018-05-14 22:48
:+1: guess we should look at getting v2.7 out fairly soon.

@bartelink I looked at options for warning on `Enrich` but couldn't come up with a quick and clean one; might be something to sort out down the track, though.

**Closed by nblumhardt** 2018-05-14 22:48 UTC
