### ISSUE TITLE
Beta 2.0.0: Finding the Right Profile

### ISSUE THREAD

**Issue by Mike-EEE** [serilog/serilog#667] opened 2016-02-14 16:32 UTC
I am currently trying to update to 2.0.0-beta-486 into my project, and I get the following message:

`Could not install package 'Serilog 2.0.0-beta-486'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

So, I am contacting the package author. :)  This is a brave new world, I understand, so please help me understand the best way to troubleshoot this issue.

It is worth noting that 1.5.14 is happy with my profile, which for convenience I will provide the selected profile here:

![](http://content.screencast.com/users/Mike-EEEE/folders/Jing/media/28709880-9bf6-438e-96c7-21787b2a386b/2016-02-14_1131.png)

Any pointers/advice on how to figure this out would be greatly appreciated!

**Comment by nblumhardt** [comment] 2016-02-16 06:03
This might be one for @khellang :-) ... I'd guess `dotnet5.1` isn't strictly compatible with `Profile7`. Not sure what the best course is for us here.

**Comment by Michael-DST** [comment] 2016-02-16 07:56
I am so cornfused... I thought ".NET Core 5" was being renamed to ".NET Core 1.0" ... is the moniker being retained for 5.0/5.1?

The other confusion is why is this working OK with my profile in 1.5x and not in the 2.0-beta?

**Comment by davidfowl** [comment] 2016-02-16 08:41
The current state of the tooling is *very* confusing. NETStandard and RC2 aims to solve these problems. Right now it's a bit of a rats nest :smile: unless you're extremely familiar with the different monikers and how they relate. https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by Michael-DST** [comment] 2016-02-16 08:53
Wow @davidfowl did we finally reach agreement on *something*? :smile:  Haha, just joking... sorta. :stuck_out_tongue: 

That looks like an excellent article and one I will take the time to digest.  Thank you for taking the time here to share that and to appease my sanity.

**Comment by khellang** [comment] 2016-02-16 13:39
I think we need to let this sit for a while, until RC2 hits. I don't think it's a good idea to start jumping through hoops to support the PCL TFMs again, only to remove them later.

**Comment by Michael-DST** [comment] 2016-02-16 13:42
Is it possible to retarget to enable 1.5.x profile compatibility, at the very least?  Or is it too much of an effort at this point?  I would like to use the latest bits and help out with testing, if possible.  As it stands I am unable to upgrade from 1.5.x to the latest beta.

**Comment by khellang** [comment] 2016-02-16 13:52
We will definitely support all the current targets when 2.0 RTMs, but right now, I think it'll be quite a bit of work to cross-compile to the old PCL profiles.

When we supported Profile259 earlier, it needed quite a few #ifdefs for the code to compile. I'm not sure we want to bring those back right now.

Hopefully, when RC2 hits, NuGet will be able to work out the relationship between `netstandard1.x` and the old PCL profiles. That's why I think we should wait until the dust settles before we start doing a lot of work to support this. `netstandard` is the way going forward, so that's what we aim to support.

If, for some reason, you won't be able to reference a `netstandard` library in a PCL, we'd have to look at alternatives, but right now, I think this is a point-in-time problem that will solve itself pretty quickly. Remember, this is still only a beta :smile:

**Comment by Michael-DST** [comment] 2016-02-16 13:58
Hey, anything for the cause to do away with #ifdef's!  After all, [# is for twitter, not for code.](https://github.com/MvvmCross/MvvmCross/wiki/The-MvvmCross-Manifesto) :P  

So it looks like my PCL's have to be updated to support `netstandard` ?   That might be my core problem.  I will look around to see if I can address this.  Thanks for your input!  You can feel free to close this issue.

**Comment by khellang** [comment] 2016-02-16 14:02
> You can feel free to close this issue.

Let's leave it open as a reminder to make sure we support the PCL profiles before RTM. We'll ping you to test :wink:

**Comment by Michael-DST** [comment] 2016-02-16 14:17
Hah!  Sure thing!

**Comment by nblumhardt** [comment] 2016-04-29 04:07
Calling this part of #590. Thanks!

**Closed by nblumhardt** 2016-04-29 04:07 UTC
Labels: v2
