### ISSUE TITLE
Ensure all Serilog owned Sinks are setup ready for .Net Core

### ISSUE THREAD

**Issue by merbla** [serilog/serilog#724] opened 2016-04-26 01:32 UTC
Ensure all the sinks have

- Dev Branch for new work
- AppVeyor builds for beta packages.

Relates to https://github.com/serilog/serilog-sinks-mongodb/pull/9

**Comment by nblumhardt** [comment] 2016-04-26 01:53
* appveyor.yml based build configuration
 * a single (or one of a small few) common build script

**Comment by nblumhardt** [comment] 2016-04-26 21:51
* verify the target framework versions are the ones we want to support (cc @khellang )

**Comment by nblumhardt** [comment] 2016-04-29 03:51
Duplicate of #590, moving there.

**Closed by nblumhardt** 2016-04-29 03:51 UTC
