### ISSUE TITLE
Push property not alway written to the log

### ISSUE THREAD

**Issue by avifatal** [serilog/serilog#1471] opened 2020-07-29 07:59 UTC
Hi,
I have a mothod that is wrapping a queue handler.
90% of the time the logs are written with the enriching properties. there are some cases that I'm losing the properties and I can't put my finger on it.
Note that everything under `method(p);` is a `sync` operation. and it is also writing to the log, assuming that the properties already set 
I don't know even where to start debugging this issue... 
This method get called when there is a new message inside the queue. and the queue is very busy.
Also note that I'm using this sink : https://github.com/manigandham/serilog-sinks-googlecloudlogging
```
public object Execute<T>(Action<object> method, IMessage<T> p) where T : BaseApiQueueModel
        {
            var service = this.GetType().Name;
            var body = p.GetBody();
            using (Log.PushProperty("Service", service))
            using (Log.PushProperty("Target", body.RequestDetails.LogId))
            using (Log.PushProperty("Env", body.RequestDetails.Environment))
            {
                var requestDetails = body.RequestDetails;
                body.RequestDetails = null;
                Log.InfoFormat("Executing with data {@data}", body);
                body.RequestDetails = requestDetails;
                try
                {
                    method(p);
                }
                catch (Exception e)
                {
                    Log.ErrorFormat("Failed with error: {@e}", e);
                    return null;
                }
                Log.Info("Done executing successfully");
                return null;
            }
        }
```
Here is the log config, (I am using a wrapper https://www.nuget.org/packages/ServiceStack.Logging.Serilog) 

```
var config = new GoogleCloudLoggingSinkOptions
            {
                ProjectId = "e-2606",
                UseJsonOutput = true,
                GoogleCredentialJson = json,
                LogName = "LogName",
                UseSourceContextAsLogName = true,
            };

            var log = new LoggerConfiguration().Enrich.FromLogContext()
                .WriteTo.GoogleCloudLogging(
                    sinkOptions: config
                ).Destructure.JsonNetTypes()
                .CreateLogger();
            LogManager.LogFactory = new SerilogFactory(log);
```

I hope I have provided enough details.

**Comment by bartelink** [comment] 2020-07-29 08:06
StackOverflow is the place for this sort of question - one key missing ingredient is your log configuration logic; the code looks fine and likely is not the issue.

As general advice/a guess, I'd suggest temporarily adding a sink to your pipeline that examines and/or stashes the properties of the LogEvent before they are passed to the sink in order to determine where they are being dropped.

**Comment by avifatal** [comment] 2020-07-29 08:24
@bartelink thanks. 
1. I added the config to the question.
2. Stackoverflow recent questions are unanswered...
3. I see in the queue that the properties are there. but ill write the entire message to the log to see this.

**Comment by bartelink** [comment] 2020-07-29 08:36
1. Looks better
2. that does not make this a better place to ask. I happened to be trawling through my notifications, but don't know how to truly solve your problem. You have waaay more chance of quick help on stackoverflow as anyone answering questions here will also see it there, and there is dramatically more traffic there
3. For me, that points the suspicion to the sink, though I'd try with and without the `.Destructure`. Again, the chances of some clicking through a link to the sink you are referring to (which most people looking in this repo are very unlikely to be using) on SO vs vs someone looking here is higher too

**Comment by avifatal** [comment] 2020-07-29 13:40
@bartelink  thank you. when I have removed the `.Destructure` all the rows were written to the log with the context.
But, the problem is now I'm getting empty jsons in the log.
Some of the objects that I'm passing are `JObject`, `JArray`, `dynamic` and plain ones.
Do you know how what do I need to do in order to be able to see all types of objects in the log?
Thanks again!

**Comment by nblumhardt** [comment] 2020-07-30 02:51
You'll need the `Destructure.JsonNetTypes()` - it would seem that for some reason the objects in question aren't being successfully converted by it, either because of a bug, or because of some quirk of those objects themselves.

If you're able to come up with a minimal reproduction, a bug report over at https://github.com/destructurama/json-net would be welcome. Thanks!

**Comment by nblumhardt** [comment] 2020-07-30 02:52
Closing here, as it looks unlikely to be a Serilog core bug at this point.

**Closed by nblumhardt** 2020-07-30 02:52 UTC
Labels: bug
