### ISSUE TITLE
CodeBase not supported

### ISSUE THREAD

**Issue by devhl-labs** [serilog/serilog#1536] opened 2021-02-09 15:51 UTC
I'm publishing my application like this:

```
dotnet publish $PSScriptRoot\..\..\src\MinionBot\MinionBot.csproj `
    -c Release `
    -o $PSScriptRoot\..\..\src\MinionBot\bin\Release\net5.0\win-x64\publish `
    -r win-x64 `
    -p:PublishReadyToRun=true `
    -p:PublishSingleFile=true
```

When running in release mode I get the following:

```
Unhandled exception. System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetNormalizedCodeBasePath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetDepsJsonPath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly, IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.DependencyModel.DependencyContext.get_Default()
   at Serilog.Settings.Configuration.Assemblies.AssemblyFinder.Auto()
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)
   at MinionBot.Program.ConfigureSerilog()
   at MinionBot.Program.Main(String[] args)
   at MinionBot.Program.<Main>(String[] args)
   ```

**Comment by nblumhardt** [comment] 2021-02-10 21:29
Thanks for the note; this is a duplicate of https://github.com/serilog/serilog-settings-configuration/issues/239 - some workarounds mentioned there.

https://github.com/serilog/serilog-settings-configuration#net-50-single-file-applications

**Closed by nblumhardt** 2021-02-10 21:29 UTC
Labels: duplicate
