### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by saitejkuralla** [serilog/serilog#1253] opened 2018-12-06 06:31 UTC
We are facing an issue on performance on logging or writing to file using serilog 
Below attachment is the delay stats between logs for each log it is taking minimum 400 ms 
Please help us on this.
![image](https://user-images.githubusercontent.com/11627655/49520626-b09d1680-f8c9-11e8-9531-4e03ae3d9d1d.png)
Below is the configuration we used for logging 
![image](https://user-images.githubusercontent.com/11627655/49520715-e641ff80-f8c9-11e8-976e-cfaf2fd2c3b6.png)

_Originally posted by @saitejkuralla in https://github.com/serilog/serilog/issues/650#issuecomment-444508504_

**Comment by merbla** [comment] 2018-12-23 23:36
Hi @saitejkuralla,

Thanks for creating the issue, however this would better live over at the [File sink issues](https://github.com/serilog/serilog-sinks-file/issues) list.

If you could provide an full sample that illustrates the problem that would be great.

Thanks!

**Comment by merbla** [comment] 2018-12-23 23:42
Closing this as it appears a dupe of #1252

**Closed by merbla** 2018-12-23 23:42 UTC
