### ISSUE TITLE
Design time error: Could not load file or assembly [VS2017]

### ISSUE THREAD

**Issue by JasperE84** [serilog/serilog#949] opened 2017-03-16 14:21 UTC
I'm getting the error below in DesignTime when I have a view open which has a viewmodel with references to SeriLog.

> Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. Het systeem kan het opgegeven bestand niet vinden. myapp C:\snip\Projects\snip\myapp\myapp\Views\MyViews\MyView.xaml
> The dutch string translated to English: "The system can't find the file"

The project compiles and runs fine, but I'd like an error-free design-time experience. What can I do to fix this error?

**Already tried:**

- Removing the serilog folder from %userprofile%.nuget and rebuilding
- Cleaning the project folder bin\ and obj\ folder
- Rebuilding the project
- Restarting VS2017
- Rebooting computer
- Another workstation shows the same error
- I'm building an UWP app targeting the anniversary edition 14393 framework.

**project.json serilog references:**

>  "Serilog": "2.4.0",
>  "Serilog.Sinks.RollingFile": "3.3.0",
> Sample VS project which replicates the issue
> 

I have created a blank Template10 project with mvvm-light viewmodel on DetailPage.xaml for which the serilog error is shown.

**Download location:**

https://www.dropbox.com/s/uocjx0kuc1dknwt/Template10_Serilog_Sample.zip?dl=0

**Screenshot of error**
![](https://i.stack.imgur.com/3VVk3.png)

**Comment by nblumhardt** [comment] 2017-03-22 22:37
Hi Jasper, thanks for the report. I suspect this is tooling/NuGet TFM-related, but don't have any suggestions. If you're able to track down the issue and it turns out to be Serilog specifically, we would happily attempt a fix here, but getting to the bottom of it is probably beyond our capacity right now.

HTH!

**Comment by JasperE84** [comment] 2017-04-01 09:23
Unfortunately despite having spent several hours on the issue I haven't been able to fix it. 
I've tried compiling Serilog, File sink and Rolling file against a netcore1.6 target with updated nuget packages, but to no avail.

**Comment by Gnitry** [comment] 2017-04-08 10:19
I have the same issue. It is very simple to reproduce: 

- create uwp project
- install serilog via nuget
- create usercontrol, write in constructor "var log = new LoggerConfiguration()"
- insert usercontrol in main page
- open main page in designer

It is interesting that if you write " if (!DesignMode.DesignModeEnabled) var log = new LoggerConfiguration();" it will not help, so problem is not in instantiation.

One of the workaround is to click button "Disable project code".

Another workaround is to download serilog project sources, add it to your solution, target project to, for example, .NetStandard1.3 and use this project as reference.

Used Visual Studio 2017 15.1

**Comment by nblumhardt** [comment] 2017-04-08 10:35
Thanks for the extra information @Gnitry. Anyone have any ideas what might cause this, and whether it's something we can solve in Serilog?

**Comment by nblumhardt** [comment] 2017-05-30 22:45
Horrible as it sounds, has anyone tried adding the .NET Framework version of Serilog.dll to the GAC to see whether it might resolve this?

Since the package works at compile and runtime without issues, I'd say this is more than likely a difference in how the UWP XAML designer is resolving references vs. how MSBuild does - so not really a Serilog issue - but happy to try to work around it if there's any option.

**Comment by Gnitry** [comment] 2017-06-28 15:02
I made a post in Microsoft forum: https://social.msdn.microsoft.com/Forums/en-US/7053a747-526e-4196-8715-399b3fdad83f/cannot-create-an-instance-of-myusercontrol1?forum=wpdevelop

**Comment by nblumhardt** [comment] 2017-06-28 21:34
Thanks @Gnitry. Did you have a chance to try the GAC solution? Cheers!

**Comment by ebashmakov** [comment] 2017-06-29 02:05
```

**Comment by ebashmakov** [comment] 2017-06-29 02:08
Do you have the binding redirect in your `app.config` (or `web.config`)?
```
      <dependentAssembly>
        <assemblyIdentity name="Serilog" publicKeyToken="24c2f752a8e58a10" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
      </dependentAssembly>
```

**Comment by Gnitry** [comment] 2017-06-29 09:18
> Did you have a chance to try the GAC solution? Cheers!
I tried:
`gacutil /i <path_to_netsdandard1.3_dll>`
Added this library as reference in UWP project.

The problem still exists.

**Comment by Gnitry** [comment] 2017-06-29 09:20
> Do you have the binding redirect in your app.config (or web.config)?

No, I don't even have these files in my project. As I know, UWP projects don't use app.config files, or am I wrong?

**Comment by ebashmakov** [comment] 2017-06-29 09:35
@Gnitry I think the binding redirects should work for UWP as well. So all you need is to add `app.config` file manually:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Serilog" publicKeyToken="24c2f752a8e58a10" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by Gnitry** [comment] 2017-07-12 13:02
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <runtime>
>     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
>       <dependentAssembly>
>         <assemblyIdentity name="Serilog" publicKeyToken="24c2f752a8e58a10" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
>       </dependentAssembly>
>     </assemblyBinding>
>   </runtime>
> </configuration>

No, It doesn't help.

**Comment by nblumhardt** [comment] 2017-07-16 23:49
https://twitter.com/WhildyBeast/status/885596253211344896 - hoping we might source some suggestions from the UWP/designer folks.

**Comment by RobAdrian** [comment] 2017-07-28 02:07
Since UWP uses Native Compilation, I would doubt that anything "binding" would help given all the linking has been performed already.  I have this issue referencing a .NetStandard 1.4 project of my own creation.  It is a simple WebRequest library that causes the UWP to vomit in the designer.  As was pointed out earlier, it appears to have ZERO to do with instantiation.  My guess is that during the attempt to bridge dependencies from UWP to .Net Standard, something "unseen" is being injected, or looked for by the tooling, and the error is simply not providing solid answers.

**Comment by nblumhardt** [comment] 2017-08-01 21:28
No response as yet from Microsoft.

Since we're using the production compilers, and the package installs/loads/runs on all of the target platforms, I think it's fair to categorize this as a problem with the UWP designer itself.

I'm closing this as "won't fix" because keeping the issue open here might create false hope that this is something Serilog can address.

If your company has a support agreement with Microsoft, and you're impacted by this issue, following up with them through that channel would be your best course of action.

I'll post any additional info here that I come across in the future. Thanks all!

**Closed by nblumhardt** 2017-08-01 21:28 UTC
Labels: discussion

**Comment by JasperE84** [comment] 2017-10-17 05:32
In my VS dev community post Microsoft has announced this issue will be fixed in the next VS release:

https://developercommunity.visualstudio.com/content/problem/35539/could-not-load-file-or-assembly-error-when-using-s.html

**Comment by nblumhardt** [comment] 2017-10-17 05:57
Fantastic news, thanks Jasper!
