### ISSUE TITLE
Adjust logging level within some thread-local/async-local context

### ISSUE THREAD

**Issue by mc0re** [serilog/serilog#1544] opened 2021-03-09 18:39 UTC
I want to adjust logging level for _Microsoft_ based on the current user. Unless I am missing something, the right way would have been to create a new class based on `LoggingLevelSwitch` - if `MinimumLevel` was `virtual`.

Can `MinimumLevel` be made `virtual`, or are there some potential issues with it? Or is there another way?

**Comment by nblumhardt** [comment] 2021-03-09 22:56
Thanks for getting in touch.

The current thread discussing this is: https://github.com/serilog/serilog/issues/1468

Duplicate of #1436, #1417, #1232, and #682

**Comment by mc0re** [comment] 2021-03-10 21:50
Thanks for taking a look.
#1417 and #1468 are the other way around. #1436 and #682 are close, but I wanted to change the level per thread, whilst the level switch is global.
As you see, there is a certain group of users that want this functionality. Maybe, there is some way of using the existing class by default, but also allowing for a more flexible, albeit costly approach?

**Comment by nblumhardt** [comment] 2021-03-10 22:30
Thanks for the follow-up. Yes, it's definitely an interesting scenario - it's just that `LoggingLevelSwitch` might not be the place to look for an implementation (for perf reasons it'll probably never have virtual or dynamically-dispatched members).

Another possibility - with a few more lines of code - would be to create a wrapper/delegating implementation of `ILogger` (let's call it `OverridableLogger` for want of a better name).

```csharp
Log.Logger = new OverridableLogger(
    new LoggerConfiguration().WriteTo.Console().CreateLogger());
```

This internally would keep an `AsyncLocal<LogEventLevel?> _minimumLevel`, and you'd provide some (probably static) methods for manipulating it in some scope:

```csharp
using (OverridableLogger.OverrideMinimumLevel(LogEventLevel.Debug))
{
    // _logger somehow descended from the root `OverridableLogger`
    _logger.Debug("helo!");
}
```

The implementation of `OverridableLogger` wouldn't have to be particularly complicated, it'd forward most methods to the underlying `ILogger` passed in its constructor, but:

 * careful implementations of `IsEnabled()` and `Write()` would need to check for a local override first, and
 * `ForContext()` would need to wrap the resulting loggers in `OverridableLogger`s too.

Couple of tips:

 * `Dispose()` would need to be implemented, and delegate to the wrapped logger if it implements `IDisposable` itself, and
 * To get an event through the underlying logger even when its level is "too low", you may need to try casting the logger to `ILogEventSink` and calling `Emit()` rather than `Write()`.

Definitely some experimentation involved, but would be really interesting to see and probably make an excellent gist to help others with the same requirements.

HTH!

**Comment by mc0re** [comment] 2021-03-13 20:58
Please, have a look at https://github.com/serilog/serilog/pull/1550. Sorry, I didn't find a "squash" option.

**Comment by nblumhardt** [comment] 2021-03-14 22:39
Thanks!

At this point, publishing a standalone gist or package along the lines described above, shaking out the API, and getting feedback, is the next step forward.

There's a lot to consider before we'd include this in the core; in just about every case now, if a feature can be implemented as an add-on, we encourage taking that approach first, and only if the add-on becomes indispensable would we bundle it/reimplement it in the _Serilog_ package.

**Comment by mc0re** [comment] 2021-03-14 23:10
It can be implemented as an add-on, but requires some modifications in the _Core_ package, would you approve that?
I don't know what _gist_ is...

**Comment by nblumhardt** [comment] 2021-03-14 23:26
Thanks for the reply! No, probably not - modifications to core all have the same high bar (we don't want to accumulate speculative extension points).

Gist is https://gist.github.com

**Comment by mc0re** [comment] 2021-03-15 16:42
If I cannot reuse `LevelOverrideMap`, I'd have to copy its implementation - do you think this is a better solution?

**Comment by mc0re** [comment] 2021-03-15 19:02
_Gist_ - something like that? https://gist.github.com/mc0re/63a377c02a344873763d13f1bcd693bb
How do you want me to add _changes_ to classes? And what to do next?

You might still want to consider incorporating my changes to `Serilog.Tests.Support.CollectingSink` to make it thread-safe.

**Comment by nblumhardt** [comment] 2021-03-16 00:18
Hi! The approach I was getting at in [this comment](https://github.com/serilog/serilog/issues/1544#issuecomment-796237121) would avoid needing to make changes to classes. The idea of a gist is that it's easy for someone with the same needs to grab the code directly, and use it in their own project.

**Comment by mc0re** [comment] 2021-03-16 07:06
Not really. One would still need to keep and handle the namespaces-specific overrides, which implies either reuse or a copy of the existing functionality of `LevelOverrideMap`.

**Comment by nblumhardt** [comment] 2021-06-08 04:19
Sorry about the slow reply, got somewhat buried! A gist is just a hosted code snippet; the usual approach is to copy/paste into the target project, but gist.github.com has a mechanism to discuss/propose changes etc. Closing as we don't have any plans to move forward on this right now, but if you need help with your implementation please drop me a line! :)

**Closed by nblumhardt** 2021-06-08 04:19 UTC
Labels: duplicate
