### ISSUE TITLE
LogContext.PushProperty does not appear to work in Serilog 2.7.1

### ISSUE THREAD

**Issue by opinionmachine** [serilog/serilog#1186] opened 2018-07-04 11:03 UTC
**A few questions before you begin:**
[SerilogTormentor.zip](https://github.com/serilog/serilog/files/2162948/SerilogTormentor.zip)

> Is this an issue related to the Serilog core project or one of the [sinks]
I can't tell, because I have to both have Serilog.Sinks.Async and Serilog at certain versions to fix the problem. 

**Does this issue relate to a new *feature* or an existing *bug*?**
- [X ] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**
Serilog 2.7.1 (and same problem exists with 2.7.2-dev-01010)
Serilog.Sinks.Async 1.3.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
If I create a dirt simple empty ASP.NET Core API project (no auth or anything) and add Serilog 2.7.1 and Serilog.Sinks.Async and Serilog.Sinks.File of the latest versions on Github yesterday, and then put together a basic middleware wrapping await _next with usings calling LogContext.PushProperty("name", value) and of course tell Serilog to Enrich.FromLogContext() and the the template to include {Properties} I get _nothing_.  IF I roll back to Serilog 2.6.0 (which means I have to roll back Serilog.Sinks.Async) everything works. 

**Please describe the expected behavior?**
I expect logcontext properties to show up in the log if included in the template. 

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
1. Create a new ASP.NET Core 2.1 Web project, choose API, no auth. 
2. Add Serilog, Serilog.Sinks.Async and a RollingFile or File sinks, or even Graylog, doesn't matte.r 
3. Tell Serilog to. Enrich.FromLogContext()
3. Configure the sink to output {Properties} in the template.
4. Add a middleware that just calls LogContext.Pushproperty, and log in the default values controller action that should value1, value2. 
5 Press F5 to run the code
6. Look in the logs. You will not find any LogContext properties in the log..

I have attached such a sample project. To make it log things, just roll back to Serilog 2.60 and the correspnding Async sink.
[SerilogTormentor.zip](https://github.com/serilog/serilog/files/2162953/SerilogTormentor.zip)

**Comment by nblumhardt** [comment] 2018-07-04 22:11
Hi! Thanks a million for providing the executable repro, much appreciated.

This is an expected behavior change introduced as [a bug-fix in 2.7](#1165). The problem with your configuration is that the enrichment (i.e. from `LogContext`) is being configured to run asynchronously:

```csharp
private static void WithConfig(WebHostBuilderContext ctx, LoggerConfiguration config)
{
    var serilogfile = ".\\tormentor-[TODAY].txt";
    config.WriteTo.Async(a =>
    {
        a.File(serilogfile.Replace("[TODAY]", DateTime.Now.Date.ToString("yyyy-MM-dd")),
                outputTemplate:
                "{Timestamp:HH:mm:ss} [{Level}] [Test: {TEST}] [Test 2: {TEST2}] CorrelationId: {CorrelationId} Message: {Message}{NewLine}{Properties}{NewLine}{Exception}")
            .Enrich.FromLogContext()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
            .MinimumLevel.Override("System", LogEventLevel.Warning);
    });
}
```

This would mean that, by the time the enricher runs (on a background thread) and looks at `LogContext`, it's probably already been `Pop()`'d.

This won't do anything at all in 2.7 with `Async()`, since although it's tricky to tell from the API, `Async()` only works for sinks. To keep the same style of config, you could use `Async(wt => wt.Logger(...))`, but that won't work quite as you expect either, because of the minimum level configuration being applied at the wrong point.

What you really want is:

```csharp
private static void WithConfig(WebHostBuilderContext ctx, LoggerConfiguration config)
{
    var serilogfile = ".\\tormentor-[TODAY].txt";
    config
        .Enrich.FromLogContext()
        .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
        .MinimumLevel.Override("System", LogEventLevel.Warning)
        .WriteTo.Async(a =>
            a.File(serilogfile.Replace("[TODAY]", DateTime.Now.Date.ToString("yyyy-MM-dd")),
                    outputTemplate:
                    "{Timestamp:HH:mm:ss} [{Level}] [Test: {TEST}] [Test 2: {TEST2}] CorrelationId: {CorrelationId} Message: {Message}{NewLine}{Properties}{NewLine}{Exception}"));
}
```

HTH!
Nick

**Comment by opinionmachine** [comment] 2018-07-04 22:37
Intuitively this makes 100% sense, and given that it "felt" like an async problem, I should have explored that. Thanks for your illuminating answer! I'll double check tomorrow my time that it works for me too, but thanks again so very much!

**Comment by nblumhardt** [comment] 2018-07-04 23:41
You're welcome 👍 

I'll close this now, but please feel free to jump back in here if you spot anything that isn't as described. Thanks!

**Closed by nblumhardt** 2018-07-04 23:41 UTC
