### ISSUE TITLE
Bug: MinimumLevel override ignores `SourceContext` of LogEvent

### ISSUE THREAD

**Issue by augustoproiete** [serilog/serilog#1382] opened 2019-11-07 00:09 UTC
The `MinimumLevel` override does not consider the `SourceContext` property defined in a `LogEvent`.

Repro:

```csharp
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .MinimumLevel.Override("MyContext", LogEventLevel.Information)
    .WriteTo.Console()
    .CreateLogger();

// Correct: DOES NOT write to sink, as expected
Log.ForContext(Serilog.Core.Constants.SourceContextPropertyName, "MyContext")
    .Verbose("If you see this, something is wrong (1)");

// Incorrect: DOES WRITE to sink
if (Log.Logger.BindMessageTemplate("If you see this, something is wrong (2)",
    propertyValues: null, out var parsedTemplate, out _))
{
    var properties = new[]
    {
        new LogEventProperty(Serilog.Core.Constants.SourceContextPropertyName,
            new ScalarValue("MyContext")),
    };

    var logEvent = new LogEvent(DateTimeOffset.Now, LogEventLevel.Verbose,
        exception: null, parsedTemplate, properties);

    // DOES WRITE to sink, but *NOT* expected
    Log.Write(logEvent);
}

```

![image](https://user-images.githubusercontent.com/177608/68348624-ce25c200-00d0-11ea-9c79-5e2d1bc701d1.png)

---

Repro full project:
* [ReproSerilogMinimumLevelOverride.zip](https://github.com/serilog/serilog/files/3817268/ReproSerilogMinimumLevelOverride.zip)

Tested:
- Serilog v2.9.0
- .NET Core 3.0 app

**Comment by skomis-mm** [comment] 2019-11-07 10:42
Hi, @caioproiete . I believe its by design. 'SourceContext' is valid in `ForContext` context, otherwise its just a regular property. 
`ForContext(..)` will create static pipeline with minimum level applied upfront for best performance. If you want to dynamically filter by property name, use filters (`.Filter(..)`) instead

**Comment by caioproiete** [comment] 2019-11-07 23:07
Thanks @skomis-mm!

I understand what you mean, and if it is indeed by design, then I think we should consider changing it.

In my view, a call to `MinimumLevel.Override` by definition should apply a `LogLevel` filter based on a property named `SourceContext` (if there is one) the same way that calling `MinimumLevel` automatically defines a filter for `LogLevel` there...

Calling `ForContext` (in my mind) should only _populate_ the `SourceContext` property for you, not do the filtering.

Does that make sense?

For instance, the code below works fine as you'd expect:

```
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .WriteTo.Console()
    .CreateLogger();

// Correct: DOES NOT write to sink, as expected
Log.Verbose("If you see this, something is wrong (1)");

// Correct: DOES NOT write to sink, as expected
if (Log.Logger.BindMessageTemplate("If you see this, something is wrong (2)",
    propertyValues: null, out var parsedTemplate, out _))
{
    var logEvent = new LogEvent(DateTimeOffset.Now, LogEventLevel.Verbose,
        exception: null, parsedTemplate, Enumerable.Empty<LogEventProperty>());

    // Correct: DOES NOT write to sink, as expected
    Log.Write(logEvent);
}
```

If `MinimumLevel` works by applying the filter defined at the root logger, then `MinimumLevel.Override` should behave the same way, considering it's applied on the same place.

**Comment by nblumhardt** [comment] 2019-11-08 04:13
Thanks for calling out the inconsistency with this, @caioproiete :+1: - we could definitely investigate further.

We left things this way in order to avoid string comparisons against `SourceContext` for every event; I don't know how much impact this would have in practice, but I suspect it could be non-trivial and it would be important to measure before we close the loophole.

Comparisons against the level, like your example above demonstrates, are much cheaper, so we do make a check there - and we committed to this behavior before adding overrides, hence the inconsistency, unfortunately.

> Calling ForContext (in my mind) should only populate the SourceContext property for you, not do the filtering.

I'm probably splitting hairs, but it's not quite like this - the goal of level overrides is to avoid constructing disabled events in the first place, hence there's no `SourceContext` property to populate (and no corresponding wasted allocations).

Cheers!

**Comment by augustoproiete** [comment] 2020-06-12 17:25
I just saw [this post on StackOverflow](https://stackoverflow.com/questions/62341787/how-can-i-override-serilog-levels-differently-for-different-sinks), and it seems the current behavior also affects sub-loggers:

```csharp
var outputTemplate = "[{Level:u3}] {SourceContext}: {Message:lj}{NewLine}";

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.File("all.log", outputTemplate: outputTemplate)

    .WriteTo.Logger(lc => lc
        .MinimumLevel.Information()
        .MinimumLevel.Override("Microsoft", Serilog.Events.LogEventLevel.Warning)
        .WriteTo.File("some.log", outputTemplate: outputTemplate))
    .CreateLogger();

var msLogger = Log.Logger.ForContext(Constants.SourceContextPropertyName, "Microsoft.AspNet.Example");
var logger = Log.Logger.ForContext(Constants.SourceContextPropertyName, "MyClass");

msLogger.Verbose("example log; should not go in the minimal file");
msLogger.Information("example log; should not go in the minimal file");
msLogger.Warning("example log");
logger.Verbose("example log; should not go in the minimal file");
logger.Information("example log");

Log.CloseAndFlush();
```

In the example above, logs of type `Information` from the `Microsoft` source context are being written to `some.log`, when they shouldn't be because of the `.MinimumLevel.Override("Microsoft", Serilog.Events.LogEventLevel.Warning)`.

**Comment by nblumhardt** [comment] 2020-06-17 07:39
Thanks for the follow-up, @augustoproiete .

Unfortunately, `MinimumLevel.Override()` is not supported at all by sub-loggers. We've updated the XDOC for `MinimumLevel.Override()` to call it out, but it seems we could still do better.

Implementing full support for it would also be great to explore, though I expect it's going to be very challenging :-)

**Comment by nblumhardt** [comment] 2023-03-29 05:17
I think this is stale, but let me know if there's still anything likely to move forward here.

**Closed by nblumhardt** 2023-03-29 05:17 UTC
Labels: discussion
