### ISSUE TITLE
Serilog.Sinks.EventLog is not compatible with .net core 1.1 app

### ISSUE THREAD

**Issue by Sam89Jha** [serilog/serilog#1008] opened 2017-07-29 16:40 UTC
Hi, I want to write my logs to windows event viewer, but the related package for serilog (Serilog.Sinks.EventLog) is not compatible with .net core 1.1 and no other info I can see on serilog site.
![image](https://user-images.githubusercontent.com/22675812/28746469-a48b6012-74aa-11e7-8f00-1e9b5ad800cf.png)

please suggest me some other package or way to write logs to windows event using serilog compatible with .net core 1.1 app

**Comment by nblumhardt** [comment] 2017-07-29 21:26
Duplicate of https://github.com/serilog/serilog-sinks-eventlog/issues/21

**Closed by nblumhardt** 2017-07-29 21:26 UTC
Labels: duplicate
