### ISSUE TITLE
Using WriteTo.RollingFile causes all logs to be discarded after it reaches fileSizeLimitBytes, so it's not rolling.

### ISSUE THREAD

**Issue by AshBay** [serilog/serilog#408] opened 2015-03-19 02:14 UTC
The bug can be easily reproduced by tweaking the integers in the following console application depending on the performance of your machine:

```
namespace SerilogSpike
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Serilog spike started");

            var config = new LoggerConfiguration()
                .WriteTo.RollingFile(@"C:\logs\Log-{Date}.txt", fileSizeLimitBytes: 1000000);
            var log = config.CreateLogger();

            int counter = 0;
            Stopwatch sw = new Stopwatch();
            sw.Start();

            while (sw.Elapsed < TimeSpan.FromSeconds(20))
            {
                log.Information("Message number " + counter);
                counter++;
                Thread.Sleep(1);
            }

            Console.WriteLine("Serilog spike stopped @ " + DateTime.Now.TimeOfDay.ToString() + " @ message number " + counter);
            Console.ReadKey();
        }
    }
}
```

By way of example, the console output indicates that the counter reached 19925 but the log file stopped saving messages at message 15090 when the file size reached 1,000,000 bytes.  If it's a rolling file log, shouldn't it delete the earliest message from the file and append the newest message to the bottom, or maybe create a new file while doing a cleanup of the old data?

**Comment by nblumhardt** [comment] 2015-03-19 07:53
Great catch, thanks very much.

We decided not to try removing old messages, since very large log files are usually caused by a runaway piece of code, and the conditions leading up to the "runaway" are at the start of the file, while the later events are generally just repetitive noise.

Cheers!

**Comment by screamish** [comment] 2015-03-20 03:34
I'm curious, what is the desired behaviour @nblumhardt?

**Comment by nblumhardt** [comment] 2015-03-21 01:14
Good point - I minsunderstood the ticket to mean that we weren't rolling on the expected roll points because of short-circuiting at the character limit, but that's not the case.

@AshBay there are definitely some trade-offs here, I think we can close this one as "by design" presently. Cheers!

**Closed by nblumhardt** 2015-03-21 01:14 UTC
Labels: bug, core, up-for-grabs

**Comment by zolakt** [comment] 2019-09-23 11:03
I'm not quite following the "by design" part. 
Shouldn't it at least roll to a new file and keep logging?
This way, you just loose a bunch of logs.

I'll give you an example. Lets say you work with a queue that gets a couple of corrupt messages. The first message in the queue will keep failing and fill the logs. Now, you manually fix that message, and the next one in queue fails as well. Without rolling to a new file, there is absolutely no way to see the new exception until tomorrow (when a new log file will be created).

Am I the only one who doesn't see any sense in this "by design" approach?

**Comment by bartelink** [comment] 2019-09-23 11:53
>We decided not to try removing old messages, since very large log files are usually caused by a runaway piece of code, and the conditions leading up to the "runaway" are at the start of the file, while the later events are generally just repetitive noise.

Seems pretty clear to me, and is what I'd like to get - I definitely wouldnt want all the evidence in the leadup destroyed because something might be getting better.

What are you suggesting the alternate behavior should be ? What design would you have ? can you suggest a name for your alternate behavior? if you can, it may be worth creating an issue that says "I'd like a feature X where I specify maxSizeButClearEveryXMinutes which would mean...." ?

**Comment by zolakt** [comment] 2019-09-23 11:59
@bartelink Don't know if this is target to me, or what? But I'm not suggesting anything getting destroyed, quite the opposite. The "by design" approach destroys everything after the limit has been breached. As simple as that. And that is not proper logging, at least in my opinion.

The alternative is not to use this sink at all, instead switch to the serilog-sinks-file, which has a rollOnFileSizeLimit option. https://github.com/serilog/serilog-sinks-file#rolling-policies

**Comment by bartelink** [comment] 2019-09-23 12:11
It was intended for you - I wanted to get a clear definition of what you do want so that the person attending to the issue would have something to start from, as opposed to a message which says "I don't like the status quo" (I've contributed to and use Serilog but am not an expert in any way; I just follow the notifications for the repo and see if I can try to help in any way, ideally by letting people who know more and hence can make better use of their scarece time by contributing to more valuable aspects of the Serilog projects workload conserve their time)

As it happens, I did not actually understand the fundamental issue (as I don't log to files with size limits in this manner); I was talking in the abstract.

As it happens, it seems the real answer here is that the `RollingFile` sink is deprecated, so I'd suggest that if the `File` sink has a behaviour you (and presumably others on this until now dormant thread) like, then the answer is to simply use that.
