### ISSUE TITLE
Flush

### ISSUE THREAD

**Issue by SebZar** [serilog/serilog#1937] opened 2023-07-14 09:25 UTC
**Is your feature request related to a problem? Please describe.**
We use buffered log files with Serilog. When we request the current log file via web we get the current log file which is missing the buffered entries. I want to flush before downloading the log file to have a full log.

**Describe the solution you'd like**
A command like "CloseAndFlush", but without "Close".

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by sungam3r** [comment] 2023-07-15 07:27
This issue looks like one for https://github.com/serilog/serilog-sinks-file repo.

**Comment by nblumhardt** [comment] 2023-07-17 05:18
Hi! This is a duplicate of https://github.com/serilog/serilog/issues/1111#issuecomment-452522381 - there's some discussion in that thread.

The "flushable logger" mentioned there is very close to `ReloadableLogger`, which didn't exist at the time, but now does:

https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/Extensions/Hosting/ReloadableLogger.cs

Using `ReloadableLogger.Reload()` when you want to flush logs should come very close to what you need.

**Closed** 2023-07-18 20:12 UTC
Labels: duplicate
